### ISSUE TITLE
Move balls away from each other when dragged on top of each other.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#100]
From the design doc:

> What happens if two balls overlap? The ball you’re dragging will get bumped away, and won’t affect the position of the other balls. Currently in Flash, both bump away.

**Comment by brandonLi8** [comment]
I played around with the flash sim. This also occurs when balls are close to each other and the mass of one increases which increases the radius to the point where the overlap. In the flash sim, both balls sort of move away from each other, but keep the COM of the balls in the same position.

I'm assuming that this feature will want to be ported to HTML5 as well, but only move the ball that is being manipulated.

**Comment by brandonLi8** [comment]
I'd also like to note that this happens when the Ball is released.

**Comment by brandonLi8** [comment]
I think this should also happen when the position of the Ball is edited in the Keypad. If the Ball's position is set to a position that overlaps with another ball, the Ball is moved.

This behavior wasn't implemented in flash, but I believe this was a bug, so I'm doing it for now in HTML5.

**Comment by brandonLi8** [comment]
This was a much harder issue than anticipated, but I worked through it in the commits above. I also made it so it is impossible to bump a ball outside of the Pool table, which was tricky when multiple balls where close together.

@arouinfar this is ready for review in master. Please review edge cases like with Balls near the edge of the pool table and bumping balls into a group of balls.

**Comment by brandonLi8** [comment]
I said that I "made it so it is impossible to bump a ball outside of the Pool table." However, edge cases kept popping up on CT. I spent all night finding new edge cases and trying to debug/ fix them, and it kept getting uglier and uglier. So I decided to scrap this; balls can be bumped to a position outside of the PoolTable.

Cases with multiple Ball bunched together still works.

**Comment by arouinfar** [comment]
@brandonLi8 when we first spoke about this issue, I was a bit apprehensive about balls being bumped completely out of bounds. Having played with the sim quite a bit since then, I'm less worried about this. It's a somewhat unlikely case, and usually there is a sliver of the ball still visible.
