### ISSUE TITLE
Constrain Elasticity to 5%

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#101]
In the design doc it states that elasticity should be constrained to 5%.

> constrainValue = 5%
No tweakers necessary. The learning goals aren’t so precise.

**Comment by brandonLi8** [comment]
Done in the commits above. Unsure if we need ticks or anything so I'm passing this to @arouinfar  to determine if this can be closed.

**Comment by arouinfar** [comment]
This looks good in master @brandonLi8. I don't think we need to add any intermediary ticks, so I'll go ahead and close.
