### ISSUE TITLE
Cursor over BallValuesPanel NumberDisplays

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#103]
In the design doc, it states to use the l-bar cursor when hovering over NumberDisplays in the BallValuesPanel:
![image](https://user-images.githubusercontent.com/42391580/84603798-7c0b0300-ae4e-11ea-8bf7-fb590265e4b2.png)

In my opinion, this cursor should be reserved for text-editor-like text boxes, because it implies that you can change the caret position and type in the middle of a string based on where the user clicks. Instead, I would prefer the current cursor "pointer":
![image](https://user-images.githubusercontent.com/42391580/84603825-ba082700-ae4e-11ea-92de-dee5644b94ab.png)
which is the one used in unit rates and projectile motion NumberDisplays that also use a Keypad.

**Comment by arouinfar** [comment]
You make a really good point @brandonLi8. Let's use the pointer.

**Comment by brandonLi8** [comment]
Thanks @arouinfar. Done in master. Closing.
