### ISSUE TITLE
Rethink decision to use vector arrows.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#104]
From https://github.com/phetsims/collision-lab/issues/93.

At the recommendation of @pixelzoom:
> I'd recommend explaining the problem to your design team, and seeing if you can come up with a design that separates the vector symbols from translated strings.

## Here is the problem
The vector symbols for both of the locations will need to be translatable (at the very least the control panel). I anticipate some RTL languages might have the parenthesis before. 

So this case is **very** different from Vector Addition, which uses a scenery Node to place an arrow on top of a single character, and combines multiple Text instances together. This approach wont work for collision lab.

I don't even want to get close to FormulaNode again. See https://github.com/phetsims/scenery/issues/457#issuecomment-526325443.

HTML entities also don't work because they don't work on all platforms, as described in #93.

----

I've been thinking about this more, and I'm not quite sure how we arrived at this decision. It seems like phet sims don't traditionally add a symbol in the control panels.

Like for instance, in masses in springs:
![image](https://user-images.githubusercontent.com/42391580/84580822-e6ad3780-ad97-11ea-81d2-5a10b95fd2d2.png)

or in gravity and orbits:
![image](https://user-images.githubusercontent.com/42391580/84580824-f298f980-ad97-11ea-8504-0cde5e80e187.png)
there isn't a separate label.

One justification for this comes from the design doc:
> This will help serve has a key for the Values strings which reference just v & p.

I think that if this was concern, this can be done without the arrow symbol, ie. 'Velocity (v)'.

I agree that the change in momentum checkbox looks uglier
![image](https://user-images.githubusercontent.com/42391580/84604113-fccafe80-ae50-11ea-93c9-c92f2153df5e.png)

But I think we can change this string to "Change in Momentum"
![image](https://user-images.githubusercontent.com/42391580/84604138-284de900-ae51-11ea-9b43-6b5d13c56830.png)

**Comment by arouinfar** [comment]
@brandonLi8 thanks for describing the issue. I do not think the abbreviation/vector symbols are necessary, so let's simplify things and go with your last suggestion:

> But I think we can change this string to "Change in Momentum"
>![image](https://user-images.githubusercontent.com/42391580/84604138-284de900-ae51-11ea-9b43-6b5d13c56830.png)

**Comment by brandonLi8** [comment]
Thanks @arouinfar. This is done in master. Closing.
