### ISSUE TITLE
Screen Icons

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#105]
I'm getting to a point where I'm running out of work to do for this sim. It might be time to start thinking about screen icons.

**Comment by arouinfar** [comment]
@brandonLi8 here are the icons we discussed in today's design meeting. If you have any questions please let me know.

![image](https://user-images.githubusercontent.com/8419308/88999780-be7b8880-d2b2-11ea-8233-de3517bca2e1.png)

**Comment by brandonLi8** [comment]
I implemented the icons in the commits above. Screenshot below.

![image](https://user-images.githubusercontent.com/42391580/89064343-105df600-d327-11ea-9791-151341b82884.png)

Back to @arouinfar for review.

**Comment by arouinfar** [comment]
Looks great @brandonLi8!
