### ISSUE TITLE
Hide the stick-slip ABSwitch?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#108]
I think I recall @ariel-phet suggesting hiding the stick-slip ABSwitch when the elasticity isn't 0. @arouinfar should I implement this?

If so, would the height of the control panel change (which would move the momenta diagram up and down)? OR would there be an empty spot for the ABSwitch so that the panel's height doesn't change?

**Comment by arouinfar** [comment]
Let's discuss at today's design meeting. 

In general, adding/removing content would change the panel's height.

**Comment by brandonLi8** [comment]
From design meeting 6/25/20, the stick-slip switch will only be present on the 4th the screen and will always be visible. Closing.
