### ISSUE TITLE
Lightweight border for when reflecting border is off.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#109]
In the design doc, it says that the 'Intro' screen has a "Viewing window w/ lightweight border" since it doesn't have a reflecting border.

@arouinfar, should I make the viewing window have a "lightweight border" when "Reflecting border" is off for the other screens as well?

**Comment by arouinfar** [comment]
@brandonLi8 if the reflecting border is off, let's use a 1pt black stroke when the Reflecting Border is off or not available on a screen.

![image](https://user-images.githubusercontent.com/8419308/85756344-f26bf880-b6cb-11ea-992f-46f5b58d6ed3.png)

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.
