### ISSUE TITLE
Collision Detection Approach

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#11]
The two references
https://www.toptal.com/game/video-game-physics-part-ii-collision-detection-for-solid-objects
https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection
should be worth reading for the development of collision-lab.

Assigning to @brandonLi8

**Comment by arouinfar** [comment]
@veillette @brandonLi8 you may want to take a look at `gas-properties`. That sim has [collision detection and response](https://github.com/phetsims/gas-properties/blob/master/doc/model.md#collision-detection-and-response) that may be helpful here.

**Comment by veillette** [comment]
The relevant part in gas-property can be found at
https://github.com/phetsims/gas-properties/blob/master/js/common/model/CollisionDetector.js

**Comment by veillette** [comment]
Because of the number of collisions and the smallness of the balls, gas properties makes some simplifications that are not going to be acceptable in collision-lab 
```
**
   * Detects and handles particle-particle collisions. Particle-particle collision are based solely whether they
   * intersect at their current locations. Is is possible (and acceptable) for two particles to pass through the
   * same point on the way to those location and not collide.
   * @param {Particle[]} particles
   * @param {Object} mutableVectors - set of mutable vectors, see this.mutableVectors in CollisionDetector constructor
   */
```

**Comment by veillette** [comment]
This document (referenced in CollisionDetector) on standard rigid-body collision looks very useful
http://web.mst.edu/~reflori/be150/Dyn%20Lecture%20Videos/Impact%20Particles%201/Impact%20Particles%201.pdf

**Comment by veillette** [comment]
We are tracking the development of the algorithm in #23. Closing
