### ISSUE TITLE
Elasticity Slider for Explore 2D

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#112]
In the design meeting 6/25/20, we decided to make the elasticity slider for Explore 2D go from 5-100% (documented in #87).

What if instead of changing the range of elasticity for different screens, we use Slider's built-in `enabledRangeProperty`.
This is used in density's mass slider:
![image](https://user-images.githubusercontent.com/42391580/85887749-98d7fc80-b7a5-11ea-8af2-06e8feb89255.png)
For the explore 2D screen, we could have the darker areas (where you can't drag the slider thumb) be from 0-5%.

We would also be able to keep the 'inelastic' and 'elastic' labels.

@arouinfar @ariel-phet thoughts?

**Comment by brandonLi8** [comment]
Btw, I added this to master and I'm sticking with it for now. It looks like
![image](https://user-images.githubusercontent.com/42391580/85955007-ee90de00-b938-11ea-9143-8bc52af5d250.png)

**Comment by arouinfar** [comment]
I think the behavior in master is nice. Using the `enabledRangeProperty` allows us to keep the "Inelastic" to "Elastic" range on all screens with the slider, which I think is preferable to using percentages for the min/max labels.
