### ISSUE TITLE
Why is there a collision lab directory

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#13]
When looking in the repo, i noticed the `/js/collision-lab` directory.

"Collision Lab" isn't a screen so why is there a `/js/collision-lab` directory?

On top of that, in the common directory there is a `CommonModel.js` and a`CommonScreenView.js`. PhET convention is to name those after the sim so it would be `CollisionLabModel.js` and `CollisionLabScreenView.js`.

<br>
I can't rename these because of the `/js/collision-lab` directory, which already contains these modules.

My proposal is to delete the `/js/collision-lab` and to create a `/js/2DLab` directory.

**Comment by brandonLi8** [comment]
In the commit above I added the Intro Screen. Holding off on adding 1D and 2D directories because of #14.

<br>

@veillette can I proceed with deleting the `collision-lab` directory and renaming `CommonScreenView` and `CommonModel` to `CollisionScreenView` and `CollisionModel` respectively?

**Comment by brandonLi8** [comment]
Because of issues in #17, (the collision-lab screen didn't declare a name), I went ahead and deleted the `collision-lab` directory.

**Comment by brandonLi8** [comment]
With the commit above, I refactored `CommonScreenView` and `CommonModel` to `CollisionScreenView` and `CollisionModel` respectively. Assigning to @veillette for review.

**Comment by veillette** [comment]
For your information, the collision-lab directory is generated automatically by the simula-rasa (since the template assumes it is a one screen simulation)

**Comment by veillette** [comment]
This looks good. closing.
 We are tracking the naming of 1DLab and 2DLab screens in a separate issue #14.
