### ISSUE TITLE
Increase width of momentum vectors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#130]
@brandonLi8 this was discussed a bit in a previous design meeting, but I don't think it ever made it onto GitHub. Currently, the momentum and velocity vectors have the exact same width, which can make it challenging to see the momentum vector. For example:
![image](https://user-images.githubusercontent.com/8419308/89080593-858cf380-d346-11ea-87d3-fb02051d589f.png) ![image](https://user-images.githubusercontent.com/8419308/89080603-8de52e80-d346-11ea-8461-036385111129.png)

Can you increase the overall size of the momentum vector so it is more visible? Here are some rough mockups. Essentially, the tail of the momentum vector is a bit wider, and the head is overall a bit larger to maintain the same rough proportions. The same changes can apply to the Change in Momentum vector too.

![image](https://user-images.githubusercontent.com/8419308/89080507-4c548380-d346-11ea-9945-36bf4ce2b358.png)  ![image](https://user-images.githubusercontent.com/8419308/89080696-d6045100-d346-11ea-999c-80b31ebe1c3b.png)

Since this polish improves usability, I think it would be nice to address before publishing a prototype.

**Comment by arouinfar** [comment]
@brandonLi8 when I created this issue, I hadn't seen https://github.com/phetsims/QA/issues/524. If this is an easy change to make, I still think it might be nice to do before publishing the prototype to the website, but I'll defer to you.

**Comment by brandonLi8** [comment]
This sounds like it should be relatively easy. Doing this next.

**Comment by brandonLi8** [comment]
Done in the commit above. Assigning back to @arouinfar for review in master.

**Comment by arouinfar** [comment]
Looks great in dev.33, thanks @brandonLi8.
