### ISSUE TITLE
Update colors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#131]
Self-assigning to experiment with [CollisionLabColors.js](https://github.com/phetsims/collision-lab/blob/master/js/common/CollisionLabColors.js).

**Comment by arouinfar** [comment]
I'll fold this into to testing https://github.com/phetsims/QA/issues/524.

**Comment by arouinfar** [comment]
For https://github.com/phetsims/QA/issues/529

I thought the ball colors could be a bit more saturated. The color momentum should also be changed since we usually reserve yellow for acceleration. I experimented locally with the colors, and found some that I think work nicely.
![Collision Lab screenshot (3)](https://user-images.githubusercontent.com/8419308/89973941-ea85fa80-dc1e-11ea-9150-42712d43472a.png)
![Collision Lab screenshot (1)](https://user-images.githubusercontent.com/8419308/89973775-6f244900-dc1e-11ea-81d9-39bc2df59e6f.png)
![Collision Lab screenshot (2)](https://user-images.githubusercontent.com/8419308/89973776-6fbcdf80-dc1e-11ea-88cf-268e8cf88bbe.png)
![Collision Lab screenshot](https://user-images.githubusercontent.com/8419308/89973777-6fbcdf80-dc1e-11ea-918a-48f9df9f1718.png)

These are color changes from the screenshots above:
``` js
BALL_COLORS: [
    new Color( 37, 221, 222 ),
    new Color( 325, 37, 173 ),
    new Color( 149, 27, 235 ),
    new Color( 235, 192, 27 )    
  ],
```

``` js
 MOMENTUM_VECTOR_FILL: 'rgb( 71, 79, 179 )',
```

@ariel-phet do these look reasonable to you? Any objections/suggestions?

**Comment by brandonLi8** [comment]
@arouinfar FYI the second color in `BALL_COLORS` (`new Color( 325, 37, 173 )`) is equivalent to `new Color( 255, 37, 173 )`) since rgb values only go up to 255.

@ariel-phet I pushed these changes to master so you can see it in action. Please close if master is good.

**Comment by arouinfar** [comment]
> @arouinfar FYI the second color in BALL_COLORS (new Color( 325, 37, 173 )) is equivalent to new Color( 255, 37, 173 )) since rgb values only go up to 255.

🤦‍♀️  Looking at my illustrator file, I meant to use `rgb(235, 37, 173)` which got corrected to `rgb(255, 37, 173)`.  However, I think it was a happy accident because a red value of 255 leads to an improved contrast between the magenta and purple balls.

**Comment by ariel-phet** [comment]
@arouinfar generally I think these work quite nicely, but I have to say I am not a big fan of the "yellow" color. It feels a bit mustard to me...could it be more orange? That feels like it would be more consistent.

**Comment by brandonLi8** [comment]
@ariel-phet we already use orange for the center-of-mass. Would it be a problem if we have colliding colors?

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet. I originally went with mustard because it was a color that doesn't already appear in the sim and is dark enough for the path to be seen against the background. 

If we want to go with something more in the vein of yellow-orange, `rgb( 248, 151, 16 )` is an option. It's a bit close to the current COM color, so I experimented with alternatives for the COM.

## Option 1: Original Color
![Collision Lab screenshot (8)](https://user-images.githubusercontent.com/8419308/90700343-d6578400-e242-11ea-9958-453691528c94.png)
![Collision Lab screenshot (9)](https://user-images.githubusercontent.com/8419308/90700349-d8b9de00-e242-11ea-99f8-311488d3e870.png)


## Option 2: Forest Green
```js
  CENTER_OF_MASS_FILL: new Color( 39, 145, 86 ),
```
![Collision Lab screenshot (1)](https://user-images.githubusercontent.com/8419308/90698431-e1f47c00-e23d-11ea-8fbd-108a3b91d194.png)
![Collision Lab screenshot](https://user-images.githubusercontent.com/8419308/90698434-e3be3f80-e23d-11ea-832f-de9a8bbb5a9f.png)

## Option 3: Red
```js
  CENTER_OF_MASS_FILL: new Color( 248, 4, 37 ),
```
![Collision Lab screenshot (2)](https://user-images.githubusercontent.com/8419308/90698629-6ba44980-e23e-11ea-9a43-e258405f8929.png)
![Collision Lab screenshot (3)](https://user-images.githubusercontent.com/8419308/90698634-6d6e0d00-e23e-11ea-8d5d-b6fa110f0cd1.png)

## Option 4: Black
```js
  CENTER_OF_MASS_FILL: Color.BLACK,
  CENTER_OF_MASS_STROKE: Color.BLACK,
```
![Collision Lab screenshot (6)](https://user-images.githubusercontent.com/8419308/90700090-26821680-e242-11ea-91a9-4fc661f421a9.png)
![Collision Lab screenshot (7)](https://user-images.githubusercontent.com/8419308/90700091-284bda00-e242-11ea-8172-9d5f6ca4c56f.png)

Personally, my preference would be to stick with mustard or go with option 1. What would you prefer @ariel-phet?

**Comment by ariel-phet** [comment]
@arouinfar I think @kathy-phet had some thoughts. We should probably have a quick collision lab meeting at design this week anyhow since it is so close to publication to finalize.

**Comment by arouinfar** [comment]
Sounds good @ariel-phet. Please include a link to this issue in the preflight.

**Comment by arouinfar** [comment]
Discussed in the 8/27/20 design meeting.

* The mustard color is too muddy. Use a more saturated version of the COM orange, `rgb( 255, 90, 0 )`
* Change COM to be a dark gray. `rgb( 70, 70, 70 )`
* Try something closer to a royal blue for momentum so its saturation is similar to velocity and has better contrast with the black used for the total momentum in the Momenta Diagram. `rgb( 50, 50, 255 )`
![Collision Lab screenshot](https://user-images.githubusercontent.com/8419308/91504466-712b1080-e88a-11ea-92ce-1b8d3d670330.png)

@kathy-phet gave these colors a 👍 over Slack.

@jonathanolson please make the following changes:
- [ ]  Ball 4: `rgb( 255, 90, 0 )`
- [ ] MOMENTUM_VECTOR_FILL: `rgb( 50, 50, 255 )`
- [ ] CENTER_OF_MASS_FILL: `rgb( 70, 70, 70 )`
- [ ]  CENTER_OF_MASS_STROKE: Color.BLACK
- [ ] Make the COM Values background transparent white to match the other value readouts.
![image](https://user-images.githubusercontent.com/8419308/91504956-a97f1e80-e88b-11ea-8a43-c1d99d34fd15.png)

**Comment by jonathanolson** [comment]
Should be complete with the above commit, can you verify?

**Comment by arouinfar** [comment]
Looks great!
