### ISSUE TITLE
Momenta Diagram zoom level doesn't return to default on ResetAll

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#133]
For https://github.com/phetsims/QA/issues/524

Steps to reproduce
1. Any screen, expand Momenta Diagram
2. Zoom all the way out
3. Reset All
4. Re-expand Momenta Diagram. Diagram is still zoomed all the way out.

**Comment by brandonLi8** [comment]
Forgot to reset the zoom Property. Done in the commit above. Closing.
