### ISSUE TITLE
Explore 2D default configuration

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#134]
For https://github.com/phetsims/QA/issues/524

I noticed the default configuration of the balls in Explore 2D has changed. Was this intentional? I think the default in dev.22 is a bit more fun.

**dev.23**
![image](https://user-images.githubusercontent.com/8419308/89083047-03ec9400-d34d-11ea-95f2-d607436a9b87.png)

**dev.22**
![image](https://user-images.githubusercontent.com/8419308/89083172-5c239600-d34d-11ea-9957-54e504947b23.png)

**Comment by brandonLi8** [comment]
Oops! I changed it when i was working on #129, but forgot to change it back. Changed it back in the commit above. Closing.
