### ISSUE TITLE
Update timeStepDuration to 0.1 s

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#135]
For https://github.com/phetsims/QA/issues/524

When stepping through a collision, things can be a bit jerky looking. We use a time step of 0.1 s in a lot of sims, and I think it works nicely here too.

@brandonLi8 if you don't have any objections, can we change `timeStepDuration` to 0.1 s?

**Comment by brandonLi8** [comment]
@arouinfar I'm assuming you meant 0.01s? I changed the default to 0.01 in the commit above (used to be 0.03). I'll assign back to you to make sure. Close if this is good.

**Comment by arouinfar** [comment]
Thanks for being a mindreader @brandonLi8! I did indeed mean 0.01 s. 🤦‍♀️ 

Looks great in dev.33!
