### ISSUE TITLE
Balls disappear if position changed with a mouse on 1D screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#138]
For https://github.com/phetsims/QA/issues/524

Observed in dev.33, but not in dev.32. Possibly related to #136?

In the Intro and Explore 1D screens, changing the position of a ball with the mouse will cause it to disappear when play is pressed. It happens if moved left or right, by a lot or just a little. The same does not occur if the position is changed with the keypad. It also doesn't seem to happen on the 2D screens, even if the position change is in 1D.

Example 1:
1. Intro screen
2. Drag Ball 1 with the mouse (direction/amount doesn't seem to matter)
3. Press play
4. Ball 1 disappears immediately

Example 2:
1. Intro screen
2. Press play
3. Grab Ball 2 and change its position
4. Ball 2 disappears as soon as it is released

**Comment by ariel-phet** [comment]
I have observed in dev.33 on the explored 2D screen. The key is to have the grid activated. Observed on multiple platforms. This will occur with multiple balls, but the simplest case to reproduce is:

1. Go to Explore 2D screen
2. Click grid on
3. Move ball 2
4. Press the Play button, ball 2 will disappear

**Comment by brandonLi8** [comment]
Should be fixed in the commit above. Back to @arouinfar  for review in master.

**Comment by arouinfar** [comment]
I didn't see this when testing the latest dev.
