### ISSUE TITLE
Updates to default ball data

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#141]
For https://github.com/phetsims/QA/issues/529

I'd like to suggest a few tweaks to the default ball data. 
- [x] Intro Screen: Set initial position of Ball 2 to 1.00 m. 
- [x] Explore 1D Screen: Set initial position of Ball 1 to -1.70 m
- [x] Explore 2D Screen: Swap the x and y components of Ball 3's initial velocity

The first two tweaks to ball positions will get rid of the overlapping velocity vectors, which I think looks nicer for an initial setup. The adjustment to Ball 3's initial velocity will make the first few collisions a bit more exciting. Currently, the balls tend to end up bouncing between the top and bottom walls.

| Before | After |
| --- | --- | 
| ![Collision Lab screenshot (5)](https://user-images.githubusercontent.com/8419308/89974599-bf040f80-dc20-11ea-92e2-662358330d65.png) | ![Collision Lab screenshot (6)](https://user-images.githubusercontent.com/8419308/89974510-882df980-dc20-11ea-9366-2ae7bb463e1c.png) | 
|![Collision Lab screenshot (8)](https://user-images.githubusercontent.com/8419308/89974516-8a905380-dc20-11ea-9b59-72dc49af292d.png) | ![Collision Lab screenshot (7)](https://user-images.githubusercontent.com/8419308/89974513-895f2680-dc20-11ea-8243-d4893eb94e5d.png) | 
| ![Collision Lab screenshot (9)](https://user-images.githubusercontent.com/8419308/89974519-8b28ea00-dc20-11ea-9d8d-8b0dd95993ad.png) | ![Collision Lab screenshot (10)](https://user-images.githubusercontent.com/8419308/89974520-8b28ea00-dc20-11ea-8ba6-b7b401e2405a.png) |

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.

**Comment by arouinfar** [comment]
It looks like the Intro screen defaults were reverted at some point. @jonathanolson can you update Ball's 2 initial position on the Intro screen to (1, 0)?

**Comment by jonathanolson** [comment]
Should be done, can you verify? (I also figured we'd want to keep the home-screen icon the same, let me know if you want it updated, it was linked in the code).

**Comment by arouinfar** [comment]
Looks good in master, @jonathanolson. Let's leave the Intro Screen icon as-is.
