### ISSUE TITLE
TimeControlNode moves a bit between screen 1 and 2

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/collision-lab#143]
@brandonLi8 the way TimeControlNode is positioned below the 1D screens it moves a bit when switching between screen 1 and 2. However, other UI components stay in their positions. My guess is that TimeControlNode is positioned in a way that is effected by the larger bounds of the collision area with the reflecting border on screen 2. 

(just flip between screen 1 and screen 2 to see the issue)

**Comment by brandonLi8** [comment]
Fixed in the commit above. Closing.
