### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#144]
To publish the prototype, we need a screenshot.

Looks like this sim doesn't have an assets folder, so it's a bit tricky for me to commit the screenshot to master and 1.0. @brandonLi8 can you take care of it?
![collision-lab-screenshot](https://user-images.githubusercontent.com/8419308/90198386-c1847780-dd8e-11ea-96e1-dc1e169c174a.png)

Please reassign to me when you're done since we'll still need alternate screenshots for publication.

**Comment by brandonLi8** [comment]
Done in the commits above.

**Comment by jonathanolson** [comment]
We had a color change after this, does that affect this screenshot?

**Comment by arouinfar** [comment]
Yes, the changes in #131 mean I'll need to retake the main screenshot. I'll do that when I take care of the alternates.

**Comment by arouinfar** [comment]
I've committed the updated screenshot and alternates, closing.
