### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#145]
Should we update credits before publishing a prototype? Currently credits are empty except for 'software development'.

**Comment by brandonLi8** [comment]
@arouinfar I published the prototype as is for now. Let me know if there are any changes and I can deploy it.

**Comment by arouinfar** [comment]
@brandonLi8 I've updated the design team credits. When this sim moves into RC, please assign to @KatieWoe to finalize the QA credits.

**Comment by KatieWoe** [comment]
QA workers for rc.1:
Kathryn Woessner, Liam Mulhall, Devon Quispe, Brooklyn Lash, Logan Bray

**Comment by jonathanolson** [comment]
Updated on master and 1.1. @arouinfar do the credits look complete?

**Comment by arouinfar** [comment]
@jonathanolson you should add yourself to the software development credits. Otherwise, looks good.

**Comment by jonathanolson** [comment]
Done. Closing!
