### ISSUE TITLE
Should PhetColorScheme be updated?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#148]
From the CRC:

> - [ ] Is [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.js) used where appropriate? Verify that the sim is not inventing/creating its own colors for things that have been standardized in 

I marked this as failing for now. I took a look at PhetColorScheme, and there are 3 things that could potentially be updated.

1. According to PhetColorScheme, acceleration is green. Luckily, there are *0* usages of this! My recommendation would be to change this to yellow and update sims like projectile motion and collision lab (and others?) to use this constant.

2.  According to PhetColorScheme, velocity is red-colorblind. Luckily, there are *0* usages of this! My recommendation would be to change this to green and update sims like projectile motion and collision lab (and others?) to use this constant.

3. There is no momentum in PhetColorScheme. We should probably add momentum using the color that collision lab is using.

@arouinfar @ariel-phet  should I proceed with this?

**Comment by ariel-phet** [comment]
@brandonLi8 yes go ahead and make this change

**Comment by arouinfar** [comment]
@brandonLi8 I opened an issue in scenery-phet for to track these changes.

**Comment by jonathanolson** [comment]
Should be good in master, @arouinfar can you verify?

**Comment by arouinfar** [comment]
Looks good in master. Thanks @jonathanolson.
