### ISSUE TITLE
Enable supportsZoom

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/collision-lab#151]
@brandonLi8 @arouinfar I tested this sim out with `?supportsZoom=true` on my phone, and I think it would be particularly useful for this sim if used on a phone when doing number entry for any of the "more data" values. Ideally we are enabling this feature for all sims going forward, but we want to check that the UI is playing nicely. In my testing it all seemed to look good, so we should go ahead and enable it within the code. 

@arouinfar assigning you in case you have any objections.

**Comment by ariel-phet** [comment]
Looking good! 

@arouinfar please close if you agree, and keep in mind for publication!

**Comment by arouinfar** [comment]
This is super nice on mobile. Let's keep it and see what happens in QA.
