### ISSUE TITLE
model.md documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/collision-lab#155]
This is fantastic! Only question is if the last sections ("Simulation State Control" and "Inelastic screen presets") need to be filled out.

https://github.com/phetsims/collision-lab/issues/153

**Comment by brandonLi8** [comment]
Thanks @jonathanolson. I forgot to mention that model.md wasn't fully finished. I'm working on it in #121, so I think this issue can be closed and I'll go ahead and fill in the last 2 sections in #121.
