### ISSUE TITLE
Some pixel polishes

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#158]
Discussed some pixel polishes with @ariel-phet on zoom today. 

- [x] Change the font for the velocity/momentum readouts on top of the balls and COM to 14.
- [x] Change the vertical spacing between the momentum vectors in the momenta diagram to 0.5 for 1D screens.
- [x] Remove the furthest zoom level (all the way zoomed out) for the momenta diagram (all screens).
- [x] Change the default to one more level zoomed in (all screens).
- [x] Add one more level of zoom-in (all screens).

**Comment by brandonLi8** [comment]
Done in the commits above.

Assigning @ariel-phet  to review in https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.5/phet/collision-lab_en_phet.html

FYI @ariel-phet @arouinfar I added the `?momentaDiagram1DSpacing` query parameter (default is 0.5) to control the vertical spacing between the vectors in 1D screens.

**Comment by arouinfar** [comment]
Looks nice in master @brandonLi8.

**Comment by ariel-phet** [comment]
I did have one further request, to keep a constant vertical spacing (in terms of pixels) between the momenta vectors on the intro and explore 1d screens. @brandonLi8 is going to make a separate issue for that work. Closing this one, since everything that was requested was done!
