### ISSUE TITLE
Consider using ES6 setters and getters.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#16]
In `Ball.js` and in `TwoVector.js` there are several helper methods that look like `getMass()` or `setMass()`.

In `VectorAddition` we used es6 getters/setters. For me personally, I prefer `set mass()` over `setMass()` especially at the call site.

@veillette thoughts?

**Comment by veillette** [comment]
I agree with @brandonLi8 . We should update tow es6 getters and setters. Leaving this issue open until we get them converted,

**Comment by veillette** [comment]
After checking through the simulation, all the getters and setters have been converted.

**Comment by brandonLi8** [comment]
Looks good, closing
