### ISSUE TITLE
Polish: make momenta diagram vectors spacing visually uniform for 1D screens.

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#164]
Apart of #158, but since it will require larger changes I'm making a separate issue.

@ariel-phet requested that the spacing between the momenta diagram vectors for 1D screens be the same visually (same number of pixels apart, rather than the same grid-spacing apart). That way, regardless of the zoom-level, they are separated the same. This shouldn't impact learning goals since the vectors can be "anywhere in space."

I said:

> Hmm, so this is probably possible but would require some refactoring (~30ish minutes?). Mainly because the momenta diagram is its own separate model, so it’s easy to sort of space them in terms of model units (grid units). What would have to be done is to also model the bounds/zoom in the model (rather than having it be a view specific thing), then calculate in grid units the spacing based on the zoom that would make it space the same visually.

I will be starting this now.

**Comment by brandonLi8** [comment]
This worked out really well. @ariel-phet please review https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.6/phet/collision-lab_en_phet.html

**Comment by ariel-phet** [comment]
Looks perfect. Closing

**Comment by arouinfar** [comment]
We reviewed this in the 8/27/20 design meeting. The uniform spacing looks great, but the total vector can be obscured by the zoom buttons when there are four balls.
![image](https://user-images.githubusercontent.com/8419308/91504029-370d3f00-e889-11ea-961c-4db68f8344ff.png)

We decided to shift all of the vectors up by half a grid to avoid the occlusion.

**Comment by jonathanolson** [comment]
I've been looking into this, and I realized that I'm not sure what the desired behavior should be for non-starting zoom levels. Presumably we wouldn't want it to be a full half-grid-square on the most-zoomed in, since then I believe the top arrow would be off of the diagram?

**Comment by arouinfar** [comment]
The y-position of the vectors on the Intro/1D screens is independent of the zoom level:
<img src="https://user-images.githubusercontent.com/8419308/93273406-0415e700-f775-11ea-8498-3cb06639c393.png" width=200> <img src="https://user-images.githubusercontent.com/8419308/93273413-0b3cf500-f775-11ea-9a06-677aa4b7a5f0.png" width=200>

I'm not sure how it's specified in the code, but could we instead reduce the padding between the vectors by 10-20%? Essentially, I'd like to reduce the padding just enough that the total is never obscured by the zoom buttons.

**Comment by jonathanolson** [comment]
Adjusted with the above commit, so the maximum fits like so:

![image](https://user-images.githubusercontent.com/480878/94488009-1e04f000-019f-11eb-80c1-44aaf331821c.png)

The default is still "centered" at the same point:

![image](https://user-images.githubusercontent.com/480878/94488061-32e18380-019f-11eb-8b4f-7c584b748fa4.png)

Thoughts on this behavior? Can you try out master and see how it feels?

**Comment by arouinfar** [comment]
Thanks @jonathanolson! It looks great in master.
