### ISSUE TITLE
User request: magnitude of velocity toggle

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/collision-lab#166]
> On the Collisions Lab, can you make the magnitude of velocity optional? Perhaps an on/off toggle? The Flash version gave signed values.
> 
> I have a lab where computing the signed change in speed across the collision is critical to developing the impulse-momentum theorem – the ratio of the change in speed per object = negative reciprocal of the mass ratio, etc. While we can just insert a negative sign during data collection, it would be nice to not have that easy-to-forget data entry chore.

**Comment by arouinfar** [comment]
> The Flash version gave signed values.

In Flash, the "Show Values" checkbox displays signed values in the Introduction tab. However, this is completely inconsistent with the behavior on the Advanced tab which displays magnitude. 
![image](https://user-images.githubusercontent.com/8419308/91773019-32a39780-eba3-11ea-99e6-243b6b565cb6.png) ![image](https://user-images.githubusercontent.com/8419308/91773040-3b946900-eba3-11ea-8f58-127f187c2e50.png)

For a more consistent experience, the "Values" checkbox in HTML5 behaves the same on all screens. It displays the magnitude of the velocity and momentum. 
![image](https://user-images.githubusercontent.com/8419308/91773194-87471280-eba3-11ea-8fdd-14ff8346385e.png)

It sounds like the user's needs are met by the "More Data" checkbox. This will display the component (and therefore signed) values of the velocity and momentum.
![image](https://user-images.githubusercontent.com/8419308/91773331-ce350800-eba3-11ea-9b86-41c32002bea6.png)
![image](https://user-images.githubusercontent.com/8419308/91772887-f5d7a080-eba2-11ea-940b-614367a86952.png)

**Comment by oliver-phet** [comment]
Replied to user with the above info. Will reopen if this won't meet their needs. Thanks @arouinfar
