### ISSUE TITLE
Kinetic Energy occluded by Values in 1D

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#168]
For https://github.com/phetsims/QA/issues/537

When the mass is large, the momentum value can occlude the Kinetic Energy readout in 1D.

![image](https://user-images.githubusercontent.com/8419308/91778942-4c4bdb80-ebb1-11ea-9896-198e1315f7d7.png)

Increasing the height of the play area by 0.1 almost entirely removes the occlusion, and doesn't seem to disturb the layout elsewhere. 
![image](https://user-images.githubusercontent.com/8419308/91779375-9c776d80-ebb2-11ea-84a9-5f4a3ac81a35.png)

There is still a very slight overlap. This could be removed entirely by instead increasing the height by 0.2, but I think that makes the play area a bit too tall for the 1D screens. Instead, it would be preferable to bump the Kinetic Energy readout down just a bit.

@jonathanolson please make the following changes:
- [x] Increase `PLAY_AREA_1D_HEIGHT` to 1.1
- [ ] Move KineticEnergyNumberDisplay down 2 px

**Comment by jonathanolson** [comment]
Both should be done, can you verify that this looks as desired?

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson!
