### ISSUE TITLE
Removed usage of CollisionLabUtils.forEachPossiblePair

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#170]
Related to #169 @jonathanolson  in 6c83cc605276e21a7cd0d9c99a7f06185075ce5f, you removed the usage of CollisionLabUtils.forEachPossiblePair.

This was used to detect collisions between every pair of balls (ie ball1 can collide with ball2 or ball3 etc.). 

However, you replaced this with
```js
    for ( let i = 1; i < this.ballSystem.balls.length; i++ ) {
      const ball1 = this.ballSystem.balls[ i - 1 ];
      const ball2 = this.ballSystem.balls[ i ];
      ...
```
which loops through each *adjacent* ball.

Loading the sim locally, as expected, most ball-ball collisions are no longer being detected, and only *adjacent* balls are being collided together (ie. ball1 and ball2 are colliding but ball1 and ball3 are not colliding).

**Comment by jonathanolson** [comment]
Yikes, thank you for noticing! I'll inspect all of the changes I made there.

**Comment by jonathanolson** [comment]
Should be fixed, can you verify? (We don't want to create closures in those situations).

**Comment by brandonLi8** [comment]
Seems find to me. Closing.
