### ISSUE TITLE
Review the migration from AxonArray to createObservableArray

### ISSUE THREAD

**Issue by samreid** [phetsims/collision-lab#173]
In https://github.com/phetsims/axon/issues/335 we migrated AxonArray => createObservableArray (which uses the Proxy).  It looks OK on my side and is passing fuzzing, but I thought it would be a good idea to request a review, since I am not familiar with the sim.  Assigning to the responsible-dev.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
