### ISSUE TITLE
Balls can overlap when adding additional ball

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#179]
Discovered in https://github.com/phetsims/QA/issues/562

@brooklynlash commented in #122:
> I noticed something similar on Windows 10 Chrome, but unsure if tunneling or just that the objects can overlap. Only works if you add balls in when the pink ball is at an area past where the new balls go in, and it looks like once they separate they don't go through each other again. 
![capacitortunnel2](https://user-images.githubusercontent.com/72031637/96742536-44721180-1380-11eb-88b4-878c05c67407.gif)

@jonathanolson it looks like it's possible for balls to overlap when adding additional balls to the system when things are in motion. There should probably be some logic that prevents this.

**Comment by KatieWoe** [comment]
I thought I typed this addition up yesterday, but I can't find it. Oops.

When the balls appear overlapping they will jump into an appropriate position if you click on them (easiest to do while paused). In contrast, if the balls overlap via a different method (dragging one ball over the other or making one ball bigger while it is up against another) then they jump into an appropriate place as soon as you let go of the control that caused the overlap.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/41024075/96896888-494fc780-144b-11eb-8998-712d881ae410.gif)

**Comment by jonathanolson** [comment]
Added logic to handle "added balls" overlap. If a different behavior for the ball interaction is desired (e.g. when a ball is dragged to another one, should they overlap until released, or otherwise), let me know.

**Comment by arouinfar** [comment]
@jonathanolson this looks good in master. I think we're ready for QA to verify in the next test.

**Comment by KatieWoe** [comment]
In 1.1.0 dev.13 the first appearance seems fixed. However, if you use the blue restart button, instead of going to the altered start position, the balls go back to the slightly buggy position they would have been in originally, and pressing play leads to a different behavior due to these new, overlapping start positions.
![overlapwithrestart](https://user-images.githubusercontent.com/41024075/103928714-78d0b080-50d9-11eb-9f48-2ad824be56f8.gif)

**Comment by brooklynlash** [comment]
I found this when testing out this issue: when a ball is near the reflecting border and you increase the mass, there is not enough space so it pops around past the other ball. @arouinfar is this intended?
![collisionmass](https://user-images.githubusercontent.com/72031637/104044144-bd1f8780-5191-11eb-81ca-dd3f73641df3.gif)

**Comment by jonathanolson** [comment]
Can you check master to see if this still occurs?

**Comment by KatieWoe** [comment]
Mainly looks fixed in master. The issue when a ball is made larger that @brooklynlash found in https://github.com/phetsims/collision-lab/issues/179#issuecomment-756887444 still occurs

**Comment by jonathanolson** [comment]
> Mainly looks fixed in master. The issue when a ball is made larger that @brooklynlash found in #179 (comment) still occurs

I believe that's a result of the current implementation, it tries to fit in the changed ball, and can swap it into a different place.

**Comment by arouinfar** [comment]
>> Mainly looks fixed in master. The issue when a ball is made larger that @brooklynlash found in [#179 (comment)](https://github.com/phetsims/collision-lab/issues/179#issuecomment-756887444) still occurs
>
>I believe that's a result of the current implementation, it tries to fit in the changed ball, and can swap it into a different place.

@jonathanolson is correct, this was intentionally done so that balls cannot overlap or escape the reflecting boundary.

**Comment by arouinfar** [comment]
@jonathanolson I don't think there's anything else that needs to be done for this issue, so back to you.

**Comment by jonathanolson** [comment]
Sounds good! I'll mark for QA verification during the next test for what I fixed.

**Comment by DevonQui** [comment]
This issue appears to be fixed when I tested it using the current version. Closing
