### ISSUE TITLE
How should we approach properties in Balls

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#18]
In #15, I removed the use of `TwoVector` and added Observable Properties:
```
      // @public (read-only) massProperty - Property of the mass of the ball (kg)
      this.massProperty = new NumberProperty( mass );

      // @public (read-only) positionPropety - Property of the center of the ball's position.
      this.positionPropety = new Vector2Property( position );

      // @public (read-only) velocityProperty - Property of the velocity of the center of mass of the ball.
      this.velocityProperty = new Vector2Property( velocity );

      //----------------------------------------------------------------------------------------
      // Handle the changing radius of the Ball based on the mass

      // @public (read-only) - Property of the radius (model) of the ball set to an arbitrary number (to be updated)
      this.radiusProperty = new NumberProperty( 0 );
```

But this raises a new question for me regarding **performance** and the use of these. If I'm understanding this correct, in `gas-properties` the "particles" don't contain these Properties.

Instead, the view also contains a "step" and relocates the ParticleNodes at each step.

Here is the documentation in `Particle.js`:
```
 * Since there can be a large number of particles, properties of particles are not implemented as observable
 * Properties.  Instead, the entire particle system is inspected to derive the current state of the system.
 * To optimize performance, all Vector2 fields herein are mutated.
```

My question is how should we approach this for Collision Theory? My preference is to stick with Observable Properties for the time being (since CollisionLab won't have as many balls). If performance issues come up, we can then switch.

**Comment by veillette** [comment]
This is legitimate concern. The rule of thumb that I have been using is to use axon properties. However, in case there is a constant animation, then use the step function in the model and in the view to send updates. The idea is that at every frame there will be an update since the balls will be moving so it is a bit pointless to have multiple listeners for the position.

**Comment by veillette** [comment]
I see that there are exceptions. For instance, in pendulumLab, the angle and angularVelocity (which will change at every step) are AXON properties. There can be two pendulum at the same time on the graph.

**Comment by brandonLi8** [comment]
@veillette since there are probably a maximum of around 5 balls, my opinion is to use the conventional PhET observable Properties **unless** there is a performance problem.

Switching between the two isn't convenient but also isn't the end of the world. How do you think we should proceed?

**Comment by veillette** [comment]
Given that the property will give us access to the old vector values, then using axon properties will allow us to get rid of twovector class.    It will be relatively easy to check for performance problems and then address it if needed. 

Let's forge ahead with your implementation of axon properties.

**Comment by veillette** [comment]
Our approach so far seems to be working well. We can reevaluate later with feedback from QA on performance.
