### ISSUE TITLE
Layering on balls/velocity arrow is not reset

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#180]
**Test device**
MacBook Air
**Operating System**
MacOS 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/562
When the sim first loads in a screen it has two balls active and shows their velocity vectors. In cases where the vectors overlap with the other ball, you can tell which is layered over the other. This layering is not reset with the reset all button.
**Steps to reproduce**
1. Reload the sim and go to the first screen
2. Note that the 2nd ball is layered over the first
3. Click the first ball to bring it to the top layer
4. Hit the reset all button and observe

**Visuals**
![resetlayering](https://user-images.githubusercontent.com/41024075/96927787-ce9ba200-1474-11eb-858b-7b2d512907d6.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.10/phet/collision-lab_all_phet.html
Version: 1.1.0-dev.10 2020-10-15 01:57:00 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1308x686
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
Should be resolved by the above commit. Can you confirm this is fixed in master?

**Comment by KatieWoe** [comment]
Looks fixed for reset all. I still see it with the scene reset button. I'm not sure if that is an issue?
![Screen Shot 2020-10-27 at 9 39 12 AM](https://user-images.githubusercontent.com/41024075/97329582-d07eb000-183c-11eb-9a53-0d98b9aff633.png)

**Comment by jonathanolson** [comment]
@arouinfar what should be done here?

**Comment by arouinfar** [comment]
@jonathanolson I think the behavior in master is fine. The goal of the scene reset is to return the objects to the most recently customized state. The z-order of the balls is immaterial. 

Not sure if this issue can be closed, or if it needs to stay open for verification of the ResetAllButton behavior in the next QA cycle, so back to @jonathanolson.

**Comment by DevonQui** [comment]
Hitting "reset all" does reset the z-order of the balls. However, hitting the "reset scene" button doesn't reset the z-order but it's clear that has not been deemed an issue for this simulation. Closing
