### ISSUE TITLE
Buffering between toolbox and reset all button

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#181]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/562
On the iPad, in both landscape and portrait mode, the momenta diagram box overlaps with the reset all button on the Explore 2D screen.

**Visuals**
![IMG_0009](https://user-images.githubusercontent.com/41024075/96930691-57b4d800-1479-11eb-9c8a-7a3f8d8b7559.PNG)

**Comment by jonathanolson** [comment]
@arouinfar do you have a preferred way of handling this? It WOULD be possible to reduce spacing/padding in the general case. However my preference would be to consider shrinking the Momenta Diagram to fit (which may take a big more logic internally). Thoughts?

**Comment by arouinfar** [comment]
This is super frustrating, and is something that QA has seen in several recent tests. For example: https://github.com/phetsims/energy-skate-park/issues/302, https://github.com/phetsims/build-a-molecule/issues/210. The default layoutBounds (which is what we design for) are based on the iPad aspect ratio so this shouldn't be happening. @jonathanolson is there some underlying common issue at play here?

For Collision Lab, I think we could shave some height off of the Momenta Diagram to get rid of the overlap.

**Comment by jonathanolson** [comment]
> @jonathanolson is there some underlying common issue at play here?

I believe it's probably just that the font is a bit taller on that platform.

**Comment by jonathanolson** [comment]
I believe I've adjusted this so it should work nicely (no overlap when viewed on my iPhone).

**Comment by KatieWoe** [comment]
Quick check looks ok on master

**Comment by KatieWoe** [comment]
Looks good in 1.1.0 dev.13 iPadOS 14.3.
