### ISSUE TITLE
CollisionLabTimeControlNode.playPauseStepButtonOptions pass the same values as defaults

### ISSUE THREAD

**Issue by zepumph** [phetsims/collision-lab#185]
In CollisionLabTimeControlNode I see:

```
      playPauseStepButtonOptions: {
        playPauseStepXSpacing: 9,
        playPauseButtonOptions: { radius: 30 },
        stepBackwardButtonOptions: { radius: 20 },
        stepForwardButtonOptions: { radius: 20 }
      },
```

The radius for stepButton by default is 20, and the radius for the play pause button is 28. Is that close enough? I don't see the value of maintaining these hard coded values in this sim, but I'm also an outsider. Feel free to do whatever is best!

I go here while working on https://github.com/phetsims/sun/issues/657

**Comment by jonathanolson** [comment]
Removed those, since the defaults seem close enough. Thank you!
