### ISSUE TITLE
Design Suggestion: Option for 5 Balls on Explore 1D

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/collision-lab#186]
A user has asked 
"Would you consider allowing five spheres on the Collisions Lab: explore 1D? I'd like five spheres because I'm interested in simulating Newton's cradle. "
I know the original had 5 and we went to 4 since we didn't see a need for 5, but this is an interesting reason to have 5. I don't know if the sim is set up to be easily extensible to 5 for the 1D situation.

**Comment by kathy-phet** [comment]
@jonathanolson - does the code naturally scale to more balls? 
@arouinfar - what do you think of the use case for 5?

**Comment by jonathanolson** [comment]
The screens are created with a maximum "internal" number of balls, which can be different than the number that are active/visible. So we can change the internal maximum easily (to 5), and also set certain screens with that number by default. Having the maximum number of balls change dynamically once a screen is created would be a bit more work.

**Comment by ariel-phet** [comment]
I am fine with 5, but doesn't seem like a huge need to me personally.

**Comment by arouinfar** [comment]
I think this is a reasonable suggestion for the Explore 1D screen and something that other teachers could find valuable. I would not include five balls on the Explore 2D screen, however.

To make room for the 5th ball, we'll need to adjust the default positions of the other balls a bit. @jonathanolson these values should work:
![image](https://user-images.githubusercontent.com/8419308/101385518-25b8d300-3879-11eb-9e62-ad6a01e7ec54.png)

**Ball 5 Data/Defaults**
* Color: `rgb( 247, 248, 16 )`
* Mass = 1.00 kg
* Position = 1.80 m
* Velocity = -1.10 m/s

Adding a 5th ball to the panel will bring it pretty close to the navbar, so we'll probably need to move the entire panel up a few px and bottom align it with the ResetAllButton. This change will affect all screens, but there should be enough room for it.

**Comment by jonathanolson** [comment]
![image](https://user-images.githubusercontent.com/480878/101667078-22098580-3a0c-11eb-92f7-0e5fe6ccebee.png)

Done in the above commit. Should the spacing for the 1d momenta diagram be reduced?

**Comment by arouinfar** [comment]
@jonathanolson looks good in master. Let's try cutting the padding between vectors in half, and see what that looks like.

**Comment by jonathanolson** [comment]
![image](https://user-images.githubusercontent.com/480878/101851259-726e0980-3b18-11eb-97e0-98970123537f.png)

This is half the padding, I'm going to try a few options and commit the best one (and then let me know if another value is better).

FYI it's `DEFAULT_1D_VERTICAL_SPACING` at the top of https://github.com/phetsims/collision-lab/blob/master/js/common/model/MomentaDiagram.js, was 0.4 before, 0.2 in the above screen-shot.

**Comment by jonathanolson** [comment]
![image](https://user-images.githubusercontent.com/480878/101851549-00e28b00-3b19-11eb-87ad-988c0992e2b0.png)
Went with 0.3, let me know if that looks ok!

**Comment by kathy-phet** [comment]
JO, just a small suggestion, Can you move the word “total” up closer to the black arrow so that it won’t overlap / be obscured by the zoom buttons it it faces to the right?

**Comment by jonathanolson** [comment]
Moved the "total" so it fits better (in the 1d cases) with the above commit.

**Comment by arouinfar** [comment]
@jonathanolson the 5th ball and its associated changes all look good in master, including the Momenta Diagram.

<img src="https://user-images.githubusercontent.com/8419308/101944537-1c49a680-3baa-11eb-947d-d7f2cea25523.png" width=300>
