### ISSUE TITLE
Balls tunnel through each other and then collide with phantom ball

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#188]
Observed in master, and likely introduced in #184 

1. Intro screen
2. Press play
3. Before the balls collide, change elasticity (value irrelevant)
4. Balls tunnel through one another, but shortly after will change their speed/momentum as though they collided with the other ball.
![tunneling](https://user-images.githubusercontent.com/8419308/101845696-8b70bd80-3b0c-11eb-8cbf-8a8f90e308af.gif)

**Comment by jonathanolson** [comment]
Investigating. The commit for that issue ONLY affects the Explore 1D screen, but I have a vague idea what might be happening.

**Comment by jonathanolson** [comment]
Thanks for finding that! I believe I've fixed it in the above commit, can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson! I'm unable to reproduce in master.
