### ISSUE TITLE
Ball can escape reflecting border if size is changed near the edge

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#189]
Basically this is #167, but instead of changing the mass near a border, toggle Constant Size.

An easy way to demonstrate the bug:
1. Explore 1D, 1 Ball, Mass 3.00 kg, Constant Size on
2. Press play, and when the ball is near the reflecting border, uncheck Constant Size
![image](https://user-images.githubusercontent.com/8419308/102131962-38e71800-3e10-11eb-809b-5e2152c3b540.png)

3. Part of the ball is now out-of-bounds, and will escape the Reflecting Border
![image](https://user-images.githubusercontent.com/8419308/102131991-43091680-3e10-11eb-9cdc-31a02f1ef9a7.png)

**Comment by jonathanolson** [comment]
Now bumping balls away from everything when constantSize is toggled. Does this look good?

**Comment by arouinfar** [comment]
Looks good in master @jonathanolson

**Comment by arouinfar** [comment]
Actually, something's not quite right @jonathanolson.

1. Explore 2D, 4 Balls, Constant Size on
2. Drag balls so they are close to one another
![image](https://user-images.githubusercontent.com/8419308/102283073-e9c3e480-3eee-11eb-8893-03937bbb8882.png)
3. Turn off constant size, and the balls repel (all good)
![image](https://user-images.githubusercontent.com/8419308/102283102-f47e7980-3eee-11eb-8137-8a28c52b8359.png)
4. Reset the observation window and the balls clump together. Looks like the new positions were not saved.
![image](https://user-images.githubusercontent.com/8419308/102283130-fea07800-3eee-11eb-9c2d-ed94a367c063.png)

**Comment by jonathanolson** [comment]
We're now explicitly saving the positions in that case with the above commit. Can you verify that this fixes it? It worked for me.

**Comment by arouinfar** [comment]
Looks good @jonathanolson!
