### ISSUE TITLE
Changing elasticity should save state

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#190]
Discovered when reviewing #183.

Currently, changing the mass, velocity, or position of a ball will save the state. However, changing the elasticity does NOT save the state, which seems really odd to me. This means that a user can set up some experiment, but if the elasticity was manipulated last, it will not be properly restored.

@jonathanolson how complicated would it be to include changes in elasticity to the conditions for saving a new state? I think for this to work, we would need to pause the sim while elasticity is changed, similar to what happens when changing the mass with the slider.

**Comment by jonathanolson** [comment]
I believe this should be handled above. It was setting the time correctly, but NOT resetting ball states. That should be fixed. Can you verify?

**Comment by arouinfar** [comment]
Looks good in master, @jonathanolson!
