### ISSUE TITLE
Small orbs can be hard to grab

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#192]
For https://github.com/phetsims/QA/issues/594. Usability note.
The mouse seems to be unable to grab the center of the balls (seen on several devices) and it seems like it might be due to the number. For the smallest radius, this can make grabbing them difficult and frustrating.

**Comment by jonathanolson** [comment]
I believe that should be fixed up by the above commit, can you verify?

**Comment by KatieWoe** [comment]
Seems fixed on the orbs, but I think the same thing may be happening with the velocity vectors where you can't grab where the letter v is.

**Comment by jonathanolson** [comment]
Can you verify that this is resolved in the above commit?

**Comment by KatieWoe** [comment]
That feels much better on master

**Comment by DevonQui** [comment]
The number on top of the orb no longer blocks user input but the part of the green vector arrow that overlays the orb still does. Besides that this issue can be closed. @jonathanolson can you confirm?

<img width="335" alt="Screen Shot 2021-01-21 at 1 25 12 PM" src="https://user-images.githubusercontent.com/72042459/105409158-45b81200-5bed-11eb-8c09-a7cf49d8db63.png">

**Comment by KatieWoe** [comment]
Good catch @DevonQui. Is there a way to make the ball grabbable under the green arrow without making the green arrow grabbable or changing the z ordering?

**Comment by jonathanolson** [comment]
I believe this was a consequence of the Accordion Box issue. In master and after that fix was applied, I believe this shouldn't be an issue. Can you verify master?

**Comment by jonathanolson** [comment]
Also applied a commit above that will ensure that if something comes up in the future, this should still work.

**Comment by DevonQui** [comment]
Tested this issue and neither the number text nor the green vector affect the user's ability to grab the balls. Closing
