### ISSUE TITLE
Constant size checkbox saving of state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#193]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Offshoot of https://github.com/phetsims/collision-lab/issues/183. Requested in https://github.com/phetsims/collision-lab/issues/183#issuecomment-757093430.
The state should probably be changed when the constant size checkbox is checked or unchecked, as it changes when and where two orbs will bounce off each other meaning that stepping back past that point can lead to a slightly wrong history. This is less drastic than other instances of this wrong history, but it is still there. Interestingly, while stepping back with the step back button takes you past the change point, the blue restart button does take you to the point where the checkbox was checked.

**Visuals**
![constantsizeproblem](https://user-images.githubusercontent.com/41024075/104223303-b185c800-5400-11eb-9b59-dd7d8878a93a.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-dev.13/phet/collision-lab_en_phet.html
Version: 1.1.0-dev.13 2021-01-06 18:20:45 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. That definitely looks a bit strange.

@jonathanolson would it be hard to add toggling the Constant Size checkbox to the laundry list of things that triggers a new saved state?

**Comment by jonathanolson** [comment]
I believe this should be handled with the above commit, can you verify?

**Comment by KatieWoe** [comment]
Looks good after a quick check on master

**Comment by loganbraywork** [comment]
Does not appear in https://github.com/phetsims/QA/issues/599
