### ISSUE TITLE
Not all of accordion panel is clickable

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/collision-lab#195]
### Test Device

MacBook Air

### Operating System

macOS 10.15.7

### Browser

Chrome 87.0.4280.141

### Problem Description

For https://github.com/phetsims/QA/issues/599. I think sims normally have the whole panel clickable. See the gifs below.

### Visuals

In Collision Lab:
![cl](https://user-images.githubusercontent.com/60749003/105255079-28793a00-5b40-11eb-8718-4fe4b5256468.gif)

In Published Gas Properties:
![gp](https://user-images.githubusercontent.com/60749003/105255095-329b3880-5b40-11eb-8579-4114bdd4a542.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.1/phet/collision-lab_en_phet.html
Version: 1.1.0-rc.1 2021-01-20 01:05:28 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Language: en-US
Window: 1200x777
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Nice find @muedli!

This looks like an issue in sun. If I open GasProps in master, the only way to open/close the AccordionBox is by clicking on the ExpandCollapseButton.

**Comment by zepumph** [comment]
Noting that this is likely the same as https://github.com/phetsims/ratio-and-proportion/issues/88. I'll promote to a common-code issue.

**Comment by jonathanolson** [comment]
This should have been fixed in master and on the branch, marking for QA verification.

**Comment by DevonQui** [comment]
This has been fixed. In all four sections of the simulation, the user is able to click anywhere on the accordion panels to open them. Closing.
