### ISSUE TITLE
Velocity circle is the same size as minimum mass ball

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#196]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/599. Connected to https://github.com/phetsims/collision-lab/issues/192, but not necessarily a bug. I'm not certain there is a good solution to this. Feel free to close.
The velocity circle that you can drag in the play area is the same size as the smallest ball size. This means that you cannot drag the smallest mass ball while at 0 velocity and paused. Instead, you grab the velocity circle and drag that. This can be mitigated by pressing play if no balls are moving, or by moving the ball then setting velocity to 0.

**Visuals**
<img width="519" alt="vsamecompare" src="https://user-images.githubusercontent.com/41024075/105415299-cc70ed00-5bf5-11eb-8e99-795f33cd7666.png">
<img width="551" alt="v0sameassmall" src="https://user-images.githubusercontent.com/41024075/105415301-cd098380-5bf5-11eb-8d20-a2f6d6a9a0c3.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.1/phet/collision-lab_en_phet.html
Version: 1.1.0-rc.1 2021-01-20 01:05:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
@arouinfar thoughts?

**Comment by jonathanolson** [comment]
I don't see an easy way, marking as wont-fix and closing.
