### ISSUE TITLE
Path continues after leaving play area

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#198]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/599.
If reflecting borders are off on the third or forth screen, and the paths are on, then once the balls leave the play area and disappear, the paths stay visible, when they should probably be behind the interface as well.

**Visuals**
![pathoffborder](https://user-images.githubusercontent.com/41024075/105426911-49599200-5c09-11eb-9d93-1833c6872150.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Collision Lab‬
URL: https://phet-dev.colorado.edu/html/collision-lab/1.1.0-rc.1/phet/collision-lab_en_phet.html
Version: 1.1.0-rc.1 2021-01-20 01:05:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Related to #200 

@jonathanolson looks like something's up with the clipping region. The out-of-bounds portion of the path should not be visible.

**Comment by jonathanolson** [comment]
Should be implement in master, @KatieWoe can you verify?

**Comment by KatieWoe** [comment]
Looks good in master

**Comment by KatieWoe** [comment]
Looks good in rc.2
