### ISSUE TITLE
Run the skipped element from new repo checklist

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#2]
The following item was skipped from the chekclist since I appear not to have the right permission
```
At https://github.com/phetsims/{{REPO}}:

 Go to Settings => Collaborators and Teams, add the teams used in another public sims (currently Design, Development, and Quality Assurance) with "Write" permissions.``
````

**Comment by brandonLi8** [comment]
@veillette do we still need to do this? I was able to push.

**Comment by veillette** [comment]
Yes we still need this such as the designer and QA can pushed to this repo

**Comment by brandonLi8** [comment]
I don't have permissions either and I'm not sure who does. Assigning @ariel-phet to do this.

**Comment by ariel-phet** [comment]
I must have done this step at some point since proper teams have access. Closing
