### ISSUE TITLE
Do we care if center of mass label overlaps with speed label?

### ISSUE THREAD

**Issue by muedli** [phetsims/collision-lab#202]
For https://github.com/phetsims/QA/issues/599.

If you have one ball, turn on center of mass, and turn on labels:
![issue](https://user-images.githubusercontent.com/60749003/105778084-d746bd00-5f28-11eb-98f8-58c9e37c4d26.png)

Looks kinda bad. Do we care?

**Comment by brooklynlash** [comment]
As a suggestion, maybe we don't have the center of mass enabled for a single ball since it will always be in the center of the ball? Or is that intended for learning?

**Comment by arouinfar** [comment]
> Looks kinda bad. Do we care?

It doesn't look great, but this is also a bit of an edge case. I don't see a clear solution that would guarantee the labels never overlap, and I don't think it's worth JO's time to investigate. @muedli I appreciate your attention to detail, but I think this is going to be a case of "don't care".

> As a suggestion, maybe we don't have the center of mass enabled for a single ball since it will always be in the center of the ball? Or is that intended for learning?

Thanks for the suggestion @brooklynlash. I think it's nice for users to be able to see the center of mass for the one-ball case, and I can imagine someone watching how the center of mass marker moves as the number of balls changes. Disabled components are also awkward for screen reader users, so we try to avoid disabling things as much as possible.
