### ISSUE TITLE
Multitouch dragging objects during reset can lead to unintended positions

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#204]
For https://github.com/phetsims/QA/issues/599. Fairly minor, feel free to close.
If you are dragging something, such as a slider or ball, and press the reset all button at the same time, the object you were dragging is not dropped.
![multitouchmass](https://user-images.githubusercontent.com/41024075/105922408-e0528f80-5ff7-11eb-8f87-012750aa9fd4.gif)

**Comment by jonathanolson** [comment]
Can you verify that the above commit fixes this?

**Comment by KatieWoe** [comment]
It now seems to freeze the sim with a console error.
<img width="955" alt="simfreeze" src="https://user-images.githubusercontent.com/41024075/106069979-d5affd00-60c0-11eb-8442-dd4d89a0b0a2.png">

**Comment by jonathanolson** [comment]
I'm not able to reproduce after spending a while on it (including setting timeouts to restart while dragging the slider, and I'm not seeing negative effects on iOS). Would it be possible to get some time on zoom where I could see this reproduced and briefly debug it?

**Comment by KatieWoe** [comment]
That sounds fine. I'll see if I can narrow it down too.

**Comment by jonathanolson** [comment]
I believe the above commit should resolve these issues (it does in my testing), can you verify?

**Comment by KatieWoe** [comment]
Issues I saw do look fixed on master

**Comment by jonathanolson** [comment]
Thanks!

**Comment by KatieWoe** [comment]
Looks good in rc.2
