### ISSUE TITLE
Checking constant size checkbox returns balls

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/collision-lab#206]
### Test Device

iPad Pro

### Operating System

iPadOS 14.4

### Browser

Safari 14.0.3

### Problem Description

For https://github.com/phetsims/QA/issues/607. If you check and uncheck the constant size checkbox on the intro screen, you'll see the balls magically return to the play area. See gif.

### Gif

![cl-issue](https://user-images.githubusercontent.com/60749003/107298417-9a072280-6a32-11eb-9d80-a997b46f39d9.gif)

**Comment by jonathanolson** [comment]
This seemed partially expected, @arouinfar what should be the behavior here? This also applies if you manually change the mass.

**Comment by arouinfar** [comment]
@jonathanolson it seems weird to me that the balls are being bumped back into the play area when there isn't a reflecting border. Ideally, if there isn't a reflecting border nothing gets bumped.

**Comment by jonathanolson** [comment]
> Ideally, if there isn't a reflecting border nothing gets bumped.

Is that a general preference for "we never bump a ball back into the play area when there is no reflecting border"?

**Comment by arouinfar** [comment]
> Is that a general preference for "we never bump a ball back into the play area when there is no reflecting border"?

Yes

**Comment by jonathanolson** [comment]
Implemented with the above commit. NOTE: Leaving myself assigned for this, since I'll need to push the commit to the release branch before the next RC. (@jessegreenberg let me know when it's ready?)

**Comment by jonathanolson** [comment]
@liam-mulhall can you verify that this is fixed in master?

**Comment by jonathanolson** [comment]
Moved the commit to the 1.1 branch.

**Comment by liam-mulhall** [comment]
Looks good on master.

**Comment by loganbraywork** [comment]
Seems to be fixed in Windows 10 Chrome and IPhone IOS14.4 Safari as of RC test https://github.com/phetsims/QA/issues/615
