### ISSUE TITLE
Fonts in Collision Lab Arabic Translation

### ISSUE THREAD

**Issue by issamali67** [phetsims/collision-lab#213]
@jbphet  Fonts in the Arabic translation of Collision Lab appear smaller. Could live with that except for the "total" label appearing in the "Momenta Diagrams", it is too small in the Arabic. I have circled in red all the terms that need slightly larger fonts in Arabic (see attached). Also attached are the English counterparts.
<img width="865" alt="CollisionLabEnglish" src="https://user-images.githubusercontent.com/64868917/122097488-f86f5380-cdcc-11eb-882c-2b24903b4ecf.png">
<img width="865" alt="CollisionLabArabic" src="https://user-images.githubusercontent.com/64868917/122097492-f907ea00-cdcc-11eb-8248-7fc7a2fa9bd3.png">

**Comment by jbphet** [comment]
@issamali67 and I worked on this during a zoom call.  The max width of the label for the "total" vector can be increased to help with that label, so I've done so.  The radio buttons that control the sim speed are a different story.  These appear a bit small because of the font size, not the max width, and @issamali67 said we should just leave them.

**Comment by jbphet** [comment]
@jonathanolson - I just cherry-picked a small commit onto the active release branch for this sim.  Can I maintenance release it or is there an active maintenance release that this would be bundled with?

**Comment by jonathanolson** [comment]
No active maintenance stuff on my end, feel free to cherry-pick or RC whenever.

**Comment by jbphet** [comment]
The maintenance release with this change is complete.  The version is 1.1.2.

The difference isn't huge, but it's noticeable.  Here are some screenshots, and notice that the label on the black arrow is now larger.

Before:
![image](https://user-images.githubusercontent.com/3082831/124325744-6ee8b100-db42-11eb-876f-b22925b5c6eb.png)

After:
![image](https://user-images.githubusercontent.com/3082831/124325706-5d9fa480-db42-11eb-8ad1-47db727a5728.png)

@issamali67 - Please have a look at the published version and, if it looks like our intended change was correctly published, please close this issue.

**Comment by issamali67** [comment]
Looks good. Will close the issue.
