### ISSUE TITLE
Should we assert types in this sim?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#26]
In `VectorAddition` we asserted types to almost all arguments. This was modeled after `gas-properties` which also does this.

Should we do the same for this sim? I think it is especially beneficial with 3 people working on the sim, so my vote is yes.

**Comment by veillette** [comment]
That served us well in vectorAddition, so we can keep using this pattern, with the understanding that whoever is writing/modifying the API should create/update the assertions.

**Comment by veillette** [comment]
Assigning to @brandonLi8 to close if he agrees with that last statement.

**Comment by brandonLi8** [comment]
Agreed. Some of the files don't assert correctly, so I'm going to keep this open to track fixing these.

**Comment by brandonLi8** [comment]
In the commits above, I have added the missing assertions. Closing.
