### ISSUE TITLE
Add mockup image to sim

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#28]
@veillette at the start of the development of `vector-addition`, you added the image of the mockup in the sim and added a slider to toggle the visibility. This was useful to help position the graph and adjust the model view scale.

Would it be possible to do the same for this sim?

**Comment by veillette** [comment]
I can add the wireframe in the design document for the 2DLab screen.

**Comment by veillette** [comment]
Assigning to @brandonLi8 to review.

**Comment by brandonLi8** [comment]
Looks good to me. We can remove this once we feel we are in a good spot. Closing for now.
