### ISSUE TITLE
User reported issue: Elasticity of 0% (Collision Lab) in 2D

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#3]
From a user:

I greatly appreciate the PhET simulations and the effort is must take to create them.

That  said, I am humbly asking for you to make a correction in the “Advanced” tab of the “Collision Lab” Simulation.

The elasticity setting of 0% does not result in a perfectly inelastic collision (objects stuck together). This however, works correctly on the “Introduction” tab (1D collision). I assume your elasticity setting is the Coefficient of Restitution (or some power of the COR).

Using perfectly inelastic collisions in 2D greatly simplifies the stage of introducing the vector nature of momentum to students. This can also be used before students have discussed energy, and still obtain predictable outcomes.

I would greatly appreciate if you could fix this in the next edition.

Other wishes for this simulation would include:
-          An option to show the path of center of mass.

-          Maybe the option to switch to the center of momentum frame of reference.

Thanks for listening and keep up the good work,

**Comment by veillette** [comment]
from https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3659

**Comment by veillette** [comment]
I have been thinking on why this feature (object sticking together) was not implemented in 2D. 
The most important effect is that in 2D, most collisions are not head on collisions. In general, in addition to forces that are imparted during collisions, collisions should generate torques as well. The torques would lead to internal rotation of the objects. For a perfectly circular object, we can easily sweep the internal rotation of the object under the rug, but for a compound object, the two stuck objects should rotate around their center of mass.

**Comment by arouinfar** [comment]
The current HTML5 design has two modes for perfectly inelastic collisions: "Slip" (Flash behavior) and "Stick". The implementation of the "Stick" behavior is being tracked in #87, so I think we can go ahead and close this issue.
