### ISSUE TITLE
Create a PlayAreaControlPanel

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#31]
![image](https://user-images.githubusercontent.com/7633344/66150354-f9555700-e5e2-11e9-9a43-114a5c8e3006.png)

The  panel should be made of checkboxes, a Number Display and a  slider,

The control Panel will be used in the three screens: intro, 1DLab, 2DLab. The controlPanel should therefore be in the common/view directory. However, in the intro screen, the  Reflecting Border and the Path checkboxes are not present.  

The slider can be created with a HSlider  (in SUN). NumberDisplay (in SCENERY_PHET) can be used to display the elasticity in a background rectangle.

The name of the properties should be in CollisionLabViewProperties.
The elastictity property lives in the model.

All the strings should be put in a file named collision-lab-strings_en.json

**Comment by alex-schor** [comment]
I added ControlPanelCheckbox and PlayAreaControlPanel, the former being a checkbox with text and a right-aligned icon. The icons for velocity and momentum are placeholders for now, but the code for ControlPanelCheckbox keeps overall spacing constant with any icon. Aesthetically, I also need to change the font size, width and background color.

**Comment by brandonLi8** [comment]
This issue is old. Since then, I have done a lot of clean up. Closing.
