### ISSUE TITLE
Add grid checkbox to CollisionLabScreenView

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#32]
GridCheckBox lives in SCENERY_PHET. 
The API created in #22 for the GridNode should be expanded to take a booleanProperty called gridVisibleProperty.

**Comment by alex-schor** [comment]
I added a GridCheckbox node to to CollisionLabScreenView and linked the grid visibility property to gridNode.

**Comment by alex-schor** [comment]
My work is completed here, assigning to @veillette for review

**Comment by veillette** [comment]
Assigning to @brandonLi8 to review.

**Comment by brandonLi8** [comment]
Integration of the grid checkbox looks good. The Property is correctly linked to the `GridVisibilityProperty` in the view properties file.
<br>
Although small, my impression is to factor out constants whenever possible. You have:
```
  ...
  top: numberOfBallsSpinner.bottom + 5,
```
as the location setter for this node, but perhaps the 5 should be factored out. 

<br>
One concern is whether or not all screens have this checkbox. Placing it in the `CollisionLabScreenView` feels a little weird, but I don't have any alternative proposals.

<br>
As for now, changing these things are relatively easy and it looks good. You have my 👍  to close this. Assigning @alex-schor to close.

**Comment by alex-schor** [comment]
The checkbox will be present in all screens. Thanks @brandonLi8 for the review. Closing.
