### ISSUE TITLE
Border Reflection and Grid

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#34]
The flash simulation did not have a grid. I was wondering what should be the behavior of the grid in the 2DLab screen, especially given that the border may or may not reflect. In the flash simulation, the border of the play area is toggled by the border reflection checkbox. My question is how should we deal with the grid when there is no border? 
Some options
 - the grid should have the same bounds regardless of the border
 - the grid should be invisible when there is no border
 - the grid should be expanded to span the width of the screen when there is no border.
 - something else?

Also in the intro screen, there is no border, so it is not clear what should be the bounds for the grid.

Assigning to @arouinfar

**Comment by veillette** [comment]
During the 10/17 meeting, it was decided that the play area should be clipped such that regardless of the toggle value for the reflection, the balls would not appear beyond the grid.

**Comment by brandonLi8** [comment]
This has been implemented. Closing.
