### ISSUE TITLE
Deviation from flash simulation: Ball being Moved.

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#37]
In the 10/17 meeting, we (KP, AR, MV) decided that if a ball is being moved, the time stepper should stop (if it is playing), and the time stepper should restart when it is dropped.

**Comment by veillette** [comment]
Assigning to @brandonLi8 to implement.

**Comment by brandonLi8** [comment]
Apologies, this is going to take a while for me to get to.

**Comment by brandonLi8** [comment]
Thanks for doing this @veillette. Is the current behavior desired? Currently, the time stepper stops and restarts when dropped as described, but should the play-pause buttons show the paused button when picked up? If not, is there anything else needed to be done here?

**Comment by brandonLi8** [comment]
The above feature has been implemented. Closing.
