### ISSUE TITLE
Visual cue for elasticity.

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#38]
In the flash simulation, the play area doesn't change when the elasticity value is modified. We know that the elasticity coefficient is related to the coefficient of restitution. The coefficient of restitution depends on many factors (speed of collision, radius of curvature of objects, etc), but to a good approximation it is a material property that is related to the hardness of material.  A material made of rubber has a low elasticity whereas a billiard ball that is very rigid has a high e value. 

I think it might be worth thinking how to give a visual clue of the elasticity. in the simulation.
It may be worth thinking about it in our next design meeting.
Two ideas I had:
- the elasticity value would be tied to the stroke of the balls. A thicker line width would indicate a smaller valuer of elasticity. 
- the elasticity of a  collision is represented by a small deformation of the ball during a collision, and the circular ball could deform to an ellipse when the collision occur.

**Comment by arouinfar** [comment]
Discussed in the 6/4/20 design meeting.

The team liked the idea of increasing the stroke weight with elasticity. A thicker stroke could indicate a rubbery coating which would be elastic.

To avoid increasing the radius of the masses, we could use an internal stroke. Here's a mockup showing a 3pt stroke weight. I would not want to go any thicker than this.

![image](https://user-images.githubusercontent.com/8419308/83832382-c5b55a00-a6a6-11ea-974e-06b0f7cbe9f3.png)

Is this the kind of stroke you were thinking of @ariel-phet?

**Comment by brandonLi8** [comment]
Implemented in the commit above. 
See https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.14/phet/collision-lab_en_phet.html

**Comment by ariel-phet** [comment]
@arouinfar @brandonLi8 yes this was the kind of stroke I was thinking

@brandonLi8 however you have the mapping a bit backwards. The thinnest stroke should be used for elastic (the example would be hard spheres, like billiard balls make nearly elastic collisions, but a thick layer of rubber would deform quite a bit, energy transforming to heat, making the collision less elastic -- so the mapping @veillette suggested was the thinnest stroke for elastic collisions and the thickest stroke for inelastic collisions)

**Comment by arouinfar** [comment]
> however you have the mapping a bit backwards

My bad @brandonLi8 @ariel-phet. I had it backwards in the meeting notes. 🤦‍♀️ 

@brandonLi8 please reverse the mapping, and I'll edit the notes.

**Comment by brandonLi8** [comment]
Reversed the linear mapping in the commit above. See https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.16/phet/collision-lab_en_phet.html. It looks like the meeting notes were updated too. Closing.
