### ISSUE TITLE
Add center-of-mass marker to play area

### ISSUE THREAD

**Issue by alex-schor** [phetsims/collision-lab#39]
We should control the visibility of the center of mass node by a property. The center of mass should only be visible when 2 or more balls are present. Also, perhaps add a velocity vector to COM depending on #9

**Comment by alex-schor** [comment]
I created a CenterOfMassNode and linked its position to the centerOfMass's position property and visibility to the centerOfMassVisibleProperty and numberOfBallsProperty. Assigning to @veillette for review.

**Comment by veillette** [comment]
I reviewed your work. We will node to update the JSDoc for the property, but let's track this in issue #41.
Closing
