### ISSUE TITLE
For documentation: prefer type-specific Properties in API definitions

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#41]
In https://github.com/phetsims/axon/issues/272,

10/24/19 dev meeting notes.

Consensus for APIs that have parameters of type Property...

Type expressions that use type-specific Properties, e.g.{BooleanProperty}, are generally undesirable, because they exclude DerivedProperty and DynamicProperty.
Specify APIs using type expressions of the form {Property.<{{TYPE}}>}.
There are 4 levels of argument type checking, see examples below. Use whichever of these strategies you prefer, depending on context.
No need to actively change existing code; apply this going forward.
````

// Example 1: no type checking
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  ...
}

// Example 2: verify that it's a Property
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property, ... );
}

// Example 3: verify that it's a Property and initial value type is correct
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property && typeof property.value === 'boolean', ... );
  ...
}

// Example 4: verify that it's a Property, initial value type is correct, guard against bad future values
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property && typeof property.value === 'boolean', ... );
  assert && property.link( value => typeof property.value === 'boolean' ;
  ...
}
````

**Comment by veillette** [comment]
We will need to retrofit our JSDoc  and assertions.

**Comment by veillette** [comment]
The standard for JSDOC of axon properties is found at https://github.com/phetsims/axon/issues/272#issuecomment-546053856

**Comment by brandonLi8** [comment]
Thanks @veillette. Ill keep an eye out for this.

**Comment by brandonLi8** [comment]
This has been mostly fixed. I will see if there are any that I need to update come self code review time. Closing.
