### ISSUE TITLE
Restart Shape looks off

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#54]
Currently Collision lab is using a custom solution for its restart button.

For some reason the arrow head looks off:
![image](https://user-images.githubusercontent.com/42391580/82380855-6c7ed280-99e6-11ea-9666-2c2c38296275.png)

Ill investigate if there are any common code reset buttons that look like this. If not, I'll go ahead and fix this.

**Comment by arouinfar** [comment]
You should be able to use the font awesome undo character for this, U+f2ea

**Comment by arouinfar** [comment]
This button also appears in gravity-and-orbits
![image](https://user-images.githubusercontent.com/8419308/82479370-82949d80-9a8f-11ea-894c-b0e0090384bd.png)

**Comment by brandonLi8** [comment]
I looked into what `gravity and orbits` does. They use an image file for this. I think I'll stick with the font-awesome character so we don't have to create an image.

**Comment by jessegreenberg** [comment]
If you are OK with the button not being rectangular, scenery-phet/ResetButton is a common component for this kind of thing. Here it is in unit-rates
![image](https://user-images.githubusercontent.com/6396244/82584470-87765180-9b62-11ea-9e22-1a9bf86493ab.png)

**Comment by brandonLi8** [comment]
Thanks @jessegreenberg. Our `FontAwesomeNode` in common code already has the `undo` icon. I'm going to go ahead and use this.

@arouinfar if you would rather use the round `scenery-phet/ResetButton`, let me know and I'll switch.

**Comment by brandonLi8** [comment]
Swapped to `FontAwesomeNode` in the commit above. The button now looks like

![image](https://user-images.githubusercontent.com/42391580/82588211-ac18fc00-9b57-11ea-9745-1ed8d4b34ce8.png)

Assigning @arouinfar to close if this is good.

**Comment by arouinfar** [comment]
Looks good in master, thanks @brandonLi8!
