### ISSUE TITLE
User reported issue: teleporting after collision

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#6]
From user:

Hello. I have found a bug when I was messing with the browser interactive at https://phet.colorado.edu/sims/collision-lab/collision-lab_en.html. If you were to choose the "advanced" tab and choose "More Data" at the bottom, then insert the data (left to right, top to bottom) "500, 2, 0, 1000, 300; 1.5, 0.343, -0.237, 0.5, 0", you get a strange result. Ball 1, upon coming into contact with ball 2, will teleport to the opposite corner with the exact opposite velocity, until it comes into contact with ball 1 again, repeating the behavior forever. I understand these parameters are outside the scope of the simulator, but I thought you should know nonetheless.

**Comment by veillette** [comment]
From https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3754

**Comment by veillette** [comment]
The source of the problem is very similar to #4, where the balls seem to go through one another when the velocity of the balls is very large.  As he user pointed out, the values for the velocity are outside the range of pedagogical useful values. We should restrict the range of allowed velocity to sensible values in the More Data table.

**Comment by brandonLi8** [comment]
In https://github.com/phetsims/collision-lab/issues/4#issuecomment-664493756, I said

> We tried limiting the velocity to 3 m/s. However, we still saw balls going through each other, because the user can infinitely increase the kinetic energy by increasing mass. We also reliable reproduced tunneling particularly when high velocity balls were stacked on top of each other and bounced off a wall (which now makes sense because our collision engine only handled one collision at a time).
>
> In #123, I addressed all of these problems by converting the collision detection to a priori (where collisions are detected beforehand) and added the ability to handle multiple collisions within a large time step.

Closing
