### ISSUE TITLE
Implementation of Ball/COM paths

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#61]
This issue will track to implementation of Ball/COM paths.

**Comment by brandonLi8** [comment]
I think I'm going to follow `gravity-and-orbits` and how they have a fading trail behind `Body` model Objects.
![image](https://user-images.githubusercontent.com/42391580/82608788-894b0f80-9b78-11ea-8f50-13fa53a1eed4.png)

I will look into how this is done.

**Comment by brandonLi8** [comment]
I looked into `gravity-and-orbits` and they use Canvas node to render this. From my understanding, at each recorded point, the canvas context draws a line to the next recorded point and linearly reduces the stroke alpha.

They also state that the use a single CanvasNode for all of the bodies for performance purposes.


@jonathanolson My question is how would you recommend I do this for `collision-lab`. Would you recommend `CanvasNode`?

Or is it even possible to draw a `Path` with different stroke colors between each line-segment? 

Assigning to get your response.

**Comment by pixelzoom** [comment]
Is it required for the Ball/COM paths to fail at the tail?  If that's not specified in the design, check with a designer before you proceed.   If it's included in the design, then...

> Would you recommend CanvasNode?

An approach like GAO seems like a reasonable starting point. 

> Or is it even possible to draw a `Path` with different stroke colors between each line-segment?

No, it's not possible to use different stroke colors (or opacity, which could also be used for the fade) for different segments of a `Path`.  There is one `{ColorDef} stroke` per `Path`.

Some other ways to do this:

(1) Is your path a straight line? If so, create a single `Path` whose stroke is a `LinearGradient`. Align the LinearGradient with the direction of the Path, and use a color stop to change the alpha channel (opacity) at the tail.

(2) Use a single `Path` to draw the part of the path that is opaque. Then implement the faded tail as a set of `Path`s with decreasing opacity.

**Comment by pixelzoom** [comment]
@brandonLi8 is there a mockup of what the ball paths are supposed to look like?  If so, please post here in a comment, and I might be able to propose other alternatives.

**Comment by arouinfar** [comment]
Here's a mockup of the paths. The closest analog might be the "Traces" in Rutherford scattering.
![image](https://user-images.githubusercontent.com/8419308/82762622-48910780-9dbf-11ea-8cff-a04aab90894e.png)

![image](https://user-images.githubusercontent.com/8419308/82762163-b556d280-9dbc-11ea-9792-29d1bccac27e.png)

Design specs:
* Trace color matches ball color
* Trace follows the ball's COM
* Trace only shows some recent time period. The time period will need to be something we tune once it's up and running. A good starting place might be 3 seconds.
* Trace uses a gradient to fade away. The mockup shows an opacity gradient (0%-100%) applied to the stroke with the fade point (not sure what it's called) located at 30%.
![image](https://user-images.githubusercontent.com/8419308/82762674-97d73800-9dbf-11ea-90f9-0a6a391e0d48.png)

**Comment by brandonLi8** [comment]
> An approach like GAO seems like a reasonable starting point.
Ok, sounds good. I will start here.

**Comment by pixelzoom** [comment]
FYI, Rutherford Scattering (which @arouinfar mentioned above) also uses CanvaNode.  Here's the bit of code that handles trail opacity in ParticleSpaceNode.js:   

```js
        if ( self.particleStyle === 'particle' ) {

            // only the last FADEOUT_SEGMENTS should be visible, map i to the opacity
            const length = particle.positions.length;
            const alpha = Utils.linear( length - FADEOUT_SEGMENTS, length, 0, 0.5, i );
            const strokeStyle = StringUtils.format( self.particleTraceColorWithFade, alpha );
            context.strokeStyle = strokeStyle;
            context.stroke();
            context.closePath();
          }
        }
```

**Comment by brandonLi8** [comment]
@arouinfar Paths have been partially implemented in master. However, I'm wondering what should happen when the user drags a ball to a different place with paths visible? Should the path draw a line from the old position to the new position? Or perhaps it should clear the current Path of the ball and start a new path from the new position? The ladder is preferred.

**Comment by brandonLi8** [comment]
@arouinfar Paths have been implemented.
 - ball paths appear when the 'Path' checkbox is checked
 - center of mass paths appear when the 'path' and 'center of mass' checkboxes are checked

I also added a query parameter to adjust how long before the paths fade: `?pathPointLifetime=`. The default value is 3 seconds at your recommendation.

Please review in master and close if there are no problems. Thanks!

**Comment by arouinfar** [comment]
@brandonLi8 the path is looking really good! You made the right call to clear the paths when the ball is moved. We might also want to clear the path of the COM too since moving a ball will shift the COM. What do you think?

**Comment by brandonLi8** [comment]
Yes I would agree.

However, this would make it super elegant (in the code) if for all user interacts with the Ball, the path of the ball and the center of mass resets, including changing the velocity vector (either by dragging the vector or through typing a new velocity). This is the behavior in flash.

So in the commit above, I went ahead and made it so that the path of the ball that is being interacted with and the COM resets on all user interaction. It also resets when the user is finished dragging the ball or typing in the keypad.

@arouinfar please review in https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.7/phet/collision-lab_en_phet.html

**Comment by brandonLi8** [comment]
After working on #76, I noticed some odd behavior of paths when the sim is "restarted." Particularly if you:
   1. Pause the sim
   2. turn paths on
   3. play the sim, the ball moves and the path is drawn as expected
   4. pause the sim
   5. restart the sim, which moves the ball back to where the ball was when the play button was pressed, and redraws the path.

Since restarting sets the elapsed time to 0, I think the restart button should clear paths.

**Comment by brandonLi8** [comment]
In the commit above, ball paths are now cleared when they are restarted. See https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.9/phet/collision-lab_en_phet.html

**Comment by arouinfar** [comment]
> Since restarting sets the elapsed time to 0, I think the restart button should clear paths.

Agreed! 

@brandonLi8 the trace looks amazing in dev.9. Nicely done!
