### ISSUE TITLE
Question: when do perfectly inelastic collisions slip?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#65]
Working on #64.

This question is not related to the implementation of stick/slip. My question is when do perfectly inelastic collisions slip?

According to [wikipedia](https://en.wikipedia.org/wiki/Inelastic_collision) "in a perfectly inelastic collision, i.e., a zero coefficient of restitution, the colliding particles stick together." I can't find any articles or sources on perfectly inelastic collisions that slip. Conservation of momentum is not violated in the current sticky inelastic collisions in master. It would seem like if two balls "slipped" off each other, it isn't a perfectly inelastic collision.Currently I don't have a clear picture of how this works, so it's even harder to try to document this.

**Comment by arouinfar** [comment]
@brandonLi8 the examples of inelastic collisions in the wiki article are in one dimension. In 1D, the balls do in fact stick together.

In 2D, things are more complicated. The Flash version of the simulation has the "Slip" behavior. For a perfectly inelastic 2D collision, the component of the velocity along the axis of the collision (black dashed line) becomes zero. 

![image](https://user-images.githubusercontent.com/8419308/82764433-e559a200-9dcb-11ea-9cf7-f415aae0fb66.png)

**Comment by brandonLi8** [comment]
Thanks @arouinfar. This issue was meant to ask a question. Closing.
