### ISSUE TITLE
Should the step-backward button be disabled for perfectly inelastic collisions

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#66]
Currently, stepping backwards works by trying to reconstruct the Balls motion by their current velocity.

This is bringing up a variety of bugs with perfectly inelastic collisions.  For instance, after a sticking perfectly inelastic collision, the balls are stuck together and moving in the same direction. Stepping the sim backwards will simply move the ball in the opposite direction. The model has no idea when they collided and doesn't know when to separate the balls.

![1231231623](https://user-images.githubusercontent.com/42391580/82714813-938b0d80-9c4d-11ea-9fb7-0d778724aff7.gif)

---

The flash sim completely avoided this issue by disabling the step-backward button for perfectly inelastic collisions. Should the HTML5 version do the same?

**Comment by arouinfar** [comment]
In Flash, the StepBackwardButton is only enabled for perfectly elastic collisions. We should follow the same pattern here and disable the button for elasticity =/= 100%.

**Comment by brandonLi8** [comment]
Thanks @arouinfar, this has been implemented in the commit above.

Since I used a workaround solution, I'm not going to close this until https://github.com/phetsims/scenery-phet/issues/563 is addressed.

**Comment by arouinfar** [comment]
@jonathanolson this issue looks stale, and given the changes in #183 we can probably close it.

**Comment by jonathanolson** [comment]
This is stale, closing.
