### ISSUE TITLE
Question: is it acceptable for a screen to have multiple ModelViewTransform instances

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#68]
Currently, collision-lab has a modelViewTransform for the general play-area

![image](https://user-images.githubusercontent.com/42391580/82716618-a1dd2780-9c55-11ea-8e52-fabfff80dea3.png)

However, now I'm working on #67, which is completely separate from the play-area and has a zoom-in and zoom-out button. I  would need to map the magnitude of a momentum vector (kg m/s) to view coordinates, from different scaling. How would I implement this? Would it be acceptable to create a separate modelViewTransform in a Property?

Assigning @jonathanolson for response.

Edit: also assigning to @pixelzoom for whoever responds first.

**Comment by pixelzoom** [comment]
You can have as many model-view transforms (MVT) per screen as you need.   And for the case you've described, you will definitely need separate MVTs for the "play area" and graph. Natural Selection has a similar requirement -- there's an MVT for the area where the bunnies move around, and there's an MVT for the Population graph.

**Comment by brandonLi8** [comment]
Ok sounds good. This issue was just meant to ask a question; the implementation will be in https://github.com/phetsims/collision-lab/issues/67 so this issue has served its purpose. Closing.
