### ISSUE TITLE
User suggestion: Collision Lab color blind

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#7]
From a user:

I am a physics/chemistry teacher in New Jersey. I very much appreciate all the simulations you guys have made, and use them a lot to introduce concepts and help students visualize phenomena. I would like to offer one suggestion. In the collision lab activity, the balls involved are red and green. A student of mine pointed out that his red-green colorblindness makes it very difficult for him to keep track of which is which. I know this doesn't affect a lot of people who would use it, but it may be helpful for those students. I appreciate everything you guys do. Thanks.

**Comment by veillette** [comment]
From https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3730

**Comment by arouinfar** [comment]
Thanks for moving the unfuddle tickets over to GitHub @veillette!

Colorblind testing is a part of our regular design process, and is included in the master checklist.  I don't think we need a separate issue for this, so closing.
