### ISSUE TITLE
Question: What is the range of the position of the Ball that the user can set

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#72]
Currently, the user can change the position of a Ball through the BallValuesPanel by clicking on a number display, which pops up a Keypad, as expected.

However, Ball's have a derived radius from a constant density, meaning their radii are often long decimals. I have it so the current range that the user can type in the Keypad is the dragging range of the ball with the grid off.

![image](https://user-images.githubusercontent.com/42391580/82837044-39748d00-9e85-11ea-8a19-8cf79444cc51.png)

As you can see, this is a very ugly looking range.

So my question is, what is the range of the Ball that the user can set via the Keypad?

**Comment by brandonLi8** [comment]
One way this could easily be solved is by using the dragging range of the Ball when the grid is visible, which rounds in to the closest grid. ie. 

![image](https://user-images.githubusercontent.com/42391580/82837187-907a6200-9e85-11ea-82a4-57fead9cd9c6.png)
this ball cannot be further dragged leftwards as it would snap to a grid position such that the left side of the ball would be outside the play area.

**Comment by arouinfar** [comment]
> One way this could easily be solved is by using the dragging range of the Ball when the grid is visible, which rounds in to the closest grid. 

Great idea @brandonLi8. Let's do this.

**Comment by brandonLi8** [comment]
Done in the commit above. The ranges are now much nicer looking. Closing.
