### ISSUE TITLE
Restart vs Reset

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#76]
It is time to implement the restart button. As far as I am aware of, these are the differences from between the reset and restart button:

 Reset: 
  - Like a traditional sim, this resets the all model Properties back to the values that they were initialized to

 Restart:
  - Pauses the sim if not already.
  - Resets the elapsed time.
  - Sets the Balls to their most recent saved state of mass, velocity, and position. Their state is saved when the sim play button is pressed. Only balls in the play area are restarted. Only balls in the play area have their state saved.

I'm going to implement this as written above for now.

**Comment by brandonLi8** [comment]
In the commits above, I added the restart functionality described above.

I should clarify one thing: the ball states are saved when the sim goes from paused to playing. This is normally achieved when the user presses the play button, but can also be achieved when the user drags a ball when the sim is playing, which pauses the sim when the user is dragging and plays it again when the user drops it (since it was playing). In this case, pressing the restart button will put the ball at the spot it was dropped.

@arouinfar please review in https://phet-dev.colorado.edu/html/collision-lab/1.0.0-dev.8/phet/collision-lab_en_phet.html

**Comment by arouinfar** [comment]
@brandonLi8 this is looking nearly perfect. The only thing that's a bit strange is that adjusting the mass with the slider will not save the state, even though editing it with the keypad does. 

What would you think about pausing the sim when the slider is adjusted? It seems like that would take care of the state saving issue.

**Comment by brandonLi8** [comment]
> What would you think about pausing the sim when the slider is adjusted? It seems like that would take care of the state saving issue.

I agree and it would work really seamlessly in the code. Doing that now.

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.
