### ISSUE TITLE
rename Path.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/collision-lab#79]
The name of collision-lab/Path.js collides with scenery/Path.js.  And the former is unfortunately the first choice for auto-import in WebStorm, which results in recurring import errors.  Could we please rename collision-lab/Path.js ?

**Comment by brandonLi8** [comment]
@pixelzoom do you have a proposal for a better name? The path shows up in the control panel
![image](https://user-images.githubusercontent.com/42391580/83192689-21a24080-a0f3-11ea-963d-ae6229bd5b2a.png)

and I believe we typically keep the naming consistent.

**Comment by brandonLi8** [comment]
The auto-importing on sublime also allows you to choose the correct version if their are name clashes.

**Comment by brandonLi8** [comment]
I guess i suppose I could rename it so something like `Trace`, but it seems weird to have `traceVisibleProperty` passed to the `pathCheckbox`. Unless the `Path` checkbox is changed to a `Trace` checkbox, which I believe would be unlikely.

**Comment by pixelzoom** [comment]
A common convention is to add a prefix when there's a name collision with common code.  So how about CollisionLabPath ?

**Comment by brandonLi8** [comment]
Ok. Renamed Path to CollisionLabPath. Closing.
