### ISSUE TITLE
What do the BallValuesPanels look like in 1D screens?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#83]
In the 2D screen, the BallValuesPanel looks like

![image](https://user-images.githubusercontent.com/42391580/83339108-ad4cd600-a287-11ea-8abb-a1a503187b4a.png)

What does it look like in the 1D Screens? Are the top labels ('position', 'velocity', 'momentum') labels still there? Are the component labels ('x', 'y', 'v_x', etc. ) there?

**Comment by arouinfar** [comment]
@brandonLi8 good question. The components aren't necessary in 1D.

The fields would be similar to Flash:
![image](https://user-images.githubusercontent.com/8419308/83712518-35faa780-a5e3-11ea-8791-09c54693aaa3.png)

If we leave the units in-line with the label, the spacing looks odd. Can we move the units below the label?

![image](https://user-images.githubusercontent.com/8419308/83713095-7575c380-a5e4-11ea-9fc4-e9c67af3ba9c.png)

**Comment by brandonLi8** [comment]
> If we leave the units in-line with the label, the spacing looks odd. Can we move the units below the label?

@arouinfar it is possible (not ideal, however) to do this.

I did give it a try locally (did not push to master as the code is ugly) . Based on your mockups, the spacing between the columns have increased when the unit is inlined.

![image](https://user-images.githubusercontent.com/42391580/83790511-8ca0c980-a655-11ea-88fd-ae0f874d5786.png)


But that increased the spacing of the mass-sliders and the mass number displays as well.
![image](https://user-images.githubusercontent.com/42391580/83790551-9c201280-a655-11ea-87d5-7bdecb53b245.png)
It also looks weird to wrap the unit to a second line here (explore 1d, more data off).

Compared to in the Explore 2D screen:
![image](https://user-images.githubusercontent.com/42391580/83790591-ab9f5b80-a655-11ea-841e-bd4f34818538.png)
the spacing is less.

It is even more ugly if we wrap separate lines in explore 1d with more data on, but not on explore 1D with more data off.

----
What if we did something like:
![Screen Shot 2020-06-04 at 11 26 57 AM](https://user-images.githubusercontent.com/42391580/83791118-84955980-a656-11ea-9c93-1ab1c82ddca4.png)
where we leave a label, but get rid of the subscripts. This is much more feasible in my opinion. We could even remove the 'x' label or just remove all labels all together (like in your first mockup). This would also leave the spacing between the mass-sliders and mass number displays the same for all screens.

@arouinfar thoughts?

**Comment by arouinfar** [comment]
@brandonLi8 here's the mockup we discussed in today's design meeting.

I've kept the heading positions the same, but re-centered the x-data.
![image](https://user-images.githubusercontent.com/8419308/83807939-13af6b00-a671-11ea-8e80-e795cc50c271.png)

**Comment by brandonLi8** [comment]
Done in the commits above.

![image](https://user-images.githubusercontent.com/42391580/84828105-c02f0c80-afe2-11ea-8694-7489d05db72a.png)
![image](https://user-images.githubusercontent.com/42391580/84828114-c3c29380-afe2-11ea-8492-7662cf451864.png)


Back to @arouinfar  for review.

**Comment by arouinfar** [comment]
Looks good, thanks @brandonLi8!
