### ISSUE TITLE
Questions on Change in Momentum

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#85]
1D screens are being implemented in #82, and I'm getting closer to implementing the change in momentum feature (or at least i'm thinking about it).

I have several questions:

![image](https://user-images.githubusercontent.com/42391580/83479375-a5db2780-a455-11ea-9fd7-3205f0c5b910.png)

(1) In the design doc, there is a picture of the momentum vectors and they are purple. However, it also states `Color matches momentum, but thicker`. Are the vectors supposed to be purple or yellow?

(2) In the design doc, it states `Change in momentum is instantaneous at the moment of collision, but isn’t around forever (not a persistent force).` The image only shows them at the instant the collision occurs. I'm assuming they pop up for longer than just one frame, and the Balls will bounce off and separate before they are removed. Do the dotted lines stay in the position of where the Ball first collided or follow the center x-coordinate of the Ball? 

(3) Where is the "Change in Momentum" text positioned? One way would be to position its centerX at the average of the tails of the momentum vectors.

(3) Do the momentum vectors pop up only on ball to ball collisions or with ball to wall collisions as well?

(4) In the design doc: "While “change in momentum” is the correct term, MD wonders if there would be issues with implicitly defining the time frame to the instant of the collision. Would the initial and final state be clear to students?" Has this been addressed?

**Comment by arouinfar** [comment]
Discussed in the 6/4/20 design meeting.

> (1) In the design doc, there is a picture of the momentum vectors and they are purple. However, it also states Color matches momentum, but thicker. Are the vectors supposed to be purple or yellow?

Same color as momentum, but still need to figure out the best color for momentum, in general.

> (2) In the design doc, it states Change in momentum is instantaneous at the moment of collision, but isn’t around forever (not a persistent force). The image only shows them at the instant the collision occurs. I'm assuming they pop up for longer than just one frame, and the Balls will bounce off and separate before they are removed. Do the dotted lines stay in the position of where the Ball first collided or follow the center x-coordinate of the Ball?

The dotted lines and vectors travel with the balls. The Change in Momentum representation will be visible for a short period of time before fading away. Let's start with 1 s, but create a query parameter so it can be easily be tuned by the team. 

> (3) Where is the "Change in Momentum" text positioned? One way would be to position its centerX at the average of the tails of the momentum vectors.

Center the `Change in Momentum` string over the collision point.

> (3) Do the momentum vectors pop up only on ball to ball collisions or with ball to wall collisions as well?

It only appears for ball-ball collisions. This representation is only available on the Intro screen, which does not have a reflecting border.

> (4) In the design doc: "While “change in momentum” is the correct term, MD wonders if there would be issues with implicitly defining the time frame to the instant of the collision. Would the initial and final state be clear to students?" Has this been addressed?

We'll learn more about this during user interviews. For now, let's continue as planned.

**Comment by brandonLi8** [comment]
In the commits above, I added a prototype (needs cleanup, possible a change in class hierarchy) for the Change in Momentum Vectors.

Here is a preview:
![ezgif-2-e76cc11c4527](https://user-images.githubusercontent.com/42391580/84065940-6d21dd80-a982-11ea-801a-8cf91ea23537.gif)

I haven't bothered with adding the "Change in Momentum" text from the mockup. @arouinfar we will probably need to rethink "Center the Change in Momentum string over the collision point" for collisions that happen with the border, and imo its way too complicated to do this for not a large gain.
----
As requested, I have added two query parameters:

`changeInMomentumVisiblePeriod` (default 0.5 seconds) is the amount of time the change in momentum vector is fully visible (opacity = 1.0) after a collision.

`changeInMomentumFadePeriod` (default 0.5 seconds) is the amount of time the change in momentum vectors linearly fade in opacity to 0 after the `changeInMomentumVisiblePeriod` has passed.


## Some other features
 - the 'Change in Momentum' vectors only appear AFTER the checkbox is checked, meaning checking the checkbox right after a collision happens doesn't show the vectors.
- The change in momentum vectors are "cleared" if the checkbox is unchecked while still visible. Immediately checking the checkbox again doesn't show the vectors until the next collision.

**Comment by brandonLi8** [comment]
There are also issues with reversing. In the commit above, I attempted to fix the most basic reversing case, but reversing past multiple collisions doesn't work. We might want to not show change in momentum vectors when reversing or think about what should happen when the sim is reversing.

**Comment by brandonLi8** [comment]
Thinking about it, I don't think should track the state of the change in momentum vector across multiple collisions since the user could change the position of the ball (via drag) while rewinding. Imo, the change in momentum vectors should be invisible when reversing except for on the exact point the Balls collide. The change in momentum vector of a ball should also be "cleared" when a user drags on that ball (or manipulates it in any way, similar to how paths clear on all user interactions with a ball). @arouinfar thoughts?

**Comment by brandonLi8** [comment]
Spoke with @arouinfar on 6/25/20 and we decided to set the elapsed time to 0 when the user manipulates any of the balls in all screens. This eliminates weird behavior when the sim is stepped backwards with change in momentum visible.

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.
