### ISSUE TITLE
User suggestion: show velocity of COM

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#9]
From the sim suggestion doc on Unfuddle:

> After using the collision lab with my kids, I had a suggestion for you: my students couldn't clearly see that the COG always moves with a constant speed. Could you add an option to see a vector arrow for the magnitude of the COG's velocity? (Otherwise, when I get up to speed on the code, you may force me to tinker with the source code myself!)

**Comment by arouinfar** [comment]
I'm not so sure if we want to display the velocity vector over the COM, but another alternative would be to show the readout of the speed when Values is checked. Marking for design meeting to check in with the team.

**Comment by arouinfar** [comment]
Discussed int eh 6/4/20 design meeting.

We decided to display the speed of the COM marker when Values in on. Off to @brandonLi8 for implementation.

**Comment by brandonLi8** [comment]
Done in the commits above.

Up to @arouinfar to decide if we should close. I think the team wanted to see it in action to decide if it was too busy or not.

**Comment by arouinfar** [comment]
Looks good @brandonLi8. I'll tag for team review at the next design meeting.

**Comment by arouinfar** [comment]
Discussed in 6/25/20 design meeting

- [ ] Change color of transparent background to match COM color
- [ ] Reduce padding between COM marker and value label to match padding used for balls

**Comment by brandonLi8** [comment]
Done in the commits above.

![image](https://user-images.githubusercontent.com/42391580/85883850-e43adc80-b79e-11ea-87f5-fb2d82d240b4.png)

Closing.
