### ISSUE TITLE
Highlight Number Displays that are being user controlled 

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#95]
Currently, number displays are highlighted yellow when typing in the keypad,
![image](https://user-images.githubusercontent.com/42391580/84549956-89958100-acc6-11ea-9e18-2b69b5c1d01b.png)
which works as intended.

However, I just noticed from the design doc that this should happen when the Ball is being dragged as well.
![image](https://user-images.githubusercontent.com/42391580/84549943-81d5dc80-acc6-11ea-948b-a44307195fbb.png)

I assuming that the velocity number displays are highlighted when the velocity vectors are dragged as well.

---- 

Implementing this feature in this issue.

**Comment by brandonLi8** [comment]
Done in the commits above. Assigning to @arouinfar  to review.

**Comment by arouinfar** [comment]
This looks really nice @brandonLi8! Good call on highlighting the v fields when adjusting the vectors. :)
