### ISSUE TITLE
label the x axis

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/collision-lab#97]
This panel shows x position:

<img width="609" alt="screenshot_397" src="https://user-images.githubusercontent.com/3046552/84595034-06357600-ae13-11ea-862d-69757c1cba7c.png">

But what is the position relative to?  There is no origin or scale shown on the x-axis here:

<img width="793" alt="screenshot_398" src="https://user-images.githubusercontent.com/3046552/84595051-1f3e2700-ae13-11ea-985f-8432f4ec4b84.png">

Playing around with the sim (with "More Data" checked), I was able to determine that the origin is the middle tick mark, and that major tick marks are spaced at 0.5 intervals.  But that's not at all obvious, and makes the x-axis almost unusable.   

Recommended to label the origin and major tick marks.

**Comment by pixelzoom** [comment]
Ah, now I see the "0.5" scale indicator.  Why is it above the panel, and not on the x axis?  

And the scale indicator doesn't help me with absolute position.

**Comment by brandonLi8** [comment]
From design meeting 6/25/20, we decided to move the ticks to the top of the Play Area for 1D screens. Doing that now.

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.
