### ISSUE TITLE
Clip Ball Values NumberDisplays?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#98]
Currently, the Ball Values NumberDisplays are never clipped.

With values on, the number displays can be seen when the ball is way outside of the pool table. This also applies to the center of mass.
![image](https://user-images.githubusercontent.com/42391580/84603256-419f6700-ae4a-11ea-8d4f-0c0424422b63.png)

Should these be clipped by the bounds of the Pool Table? Or we could make them invisible if the ball's center exits the pool table, similar to how the velocity/momentum vectors and the change in momentum vectors are clipped.

**Comment by brandonLi8** [comment]
Also, from looking at the ss above, should the center of mass 'x' be clipped as well?

**Comment by arouinfar** [comment]
> Should these be clipped by the bounds of the Pool Table? Or we could make them invisible if the ball's center exits the pool table, similar to how the velocity/momentum vectors and the change in momentum vectors are clipped.

@brandonLi8 I think either of these options would work, but I prefer the latter for a few reasons
* Consistent behavior with the vectors
* Labels won't get clipped when the ball bounces off one of the borders.

**Comment by brandonLi8** [comment]
Done in the commit above. Closing.
