### ISSUE TITLE
Aspect ratio of the Pool Tables

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#99]
A while back, the aspect ratio of the pool tables was discussed [here](https://docs.google.com/document/d/1FwMnpv8LyMZfMYPcASYhI2jtgCXyWrgAjTOx3Po_MsE/edit#bookmark=id.uexpge996qq). It doesn't look a decision was made, so I'm making this issue.

Currently, the grid is 8x4 for explore 2D and 8x2 for 1D screens. I'd also like to note that we should probably keep the dimensions even so the origin is in the center.

Also, in the mockups, the grid for explore 2D is 8 blocks long but 9 blocks long for 1D screens. Unsure if this is intentional. 

Edit: I would also like to mention that we have more vertical space now that there are only 4 balls maximum since the BallValuesPanel's has a smaller height.

**Comment by arouinfar** [comment]
@brandonLi8 I reviewed master, and I think the current size and aspect ratio of the 2D grid looks good. Let's continue with the 8x4 grid so the origin is centered.

For 1D, it would be really nice if we could have a 2x9 grid. Tagging for design meeting for disucssion.

**Comment by arouinfar** [comment]
On second thought, the origin centering would be an issue for the 2x9 grid.

Keeping this tagged for design meeting so the team is aware.

**Comment by brandonLi8** [comment]
Spoke with @arouinfar on 6/25/20, and we decided to leave the aspect ratio as-is on master. Closing.
